### ISSUE TITLE
Getting list of projects takes quite some time

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#1009]
It takes over 10 seconds to load the project list. Could this be related to the check to see which repos the user has access to?

![image](https://user-images.githubusercontent.com/2754461/41594060-f3203b3c-7376-11e8-9244-ed295f6c4d5a.png)

**Comment by KrauseFx** [comment]
Yes, this is something we really have to fix, and I think you're right! Right now we're listing all the user's repo every time you list all the projects. This is very slow on accounts with write access to many repos. When working on fixing this (e.g. by caching) we have to make sure to consider the user gets access revoked use case https://github.com/fastlane/ci/blob/master/docs/use_cases/user_gets_revoked.md
