### ISSUE TITLE
Endpoint to create an Account given an API Token

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#1013]
Parent: #1011 

POST endpoint to create a user. Input should be an API Token and password. The email should be pulled from the API token and be used as the user ID.

This endpoint should login the new user by returning a JWT token.

```json
{
  "api_token": "234",
  "password": "456"
}
```

**Comment by nakhbari** [comment]
@KrauseFx Could you help me out with this?

**Comment by KrauseFx** [comment]
Yes, I can take that on today 👍

**Comment by KrauseFx** [comment]
> This endpoint should login the new user by returning a JWT token.

I don't think that's a good idea. We probably will have some kind of user management at some point, which ideally uses the same API endpoint I guess? I believe we should let the frontend do 2 requests:

1. Create the user
1. Login
