### ISSUE TITLE
Onboarding workflow fails with "Repository creation failed; message: name already exists on this account" when trying to set FASTLANE_CI_REPO_URL

### ISSUE THREAD

**Issue by bogdanbrato** [fastlane/ci#1019]
Here's what I've done: 
`rm -rf ~\.fastlane` 
`set FASTLANE_CI_ERB_CLIENT=1`
`bundle exec rackup`

I then followed the onboarding process until the page where `FASTLANE_CI_REPO_URL` is set. I tried to set FASTLANE_CI_REPO_URL to a repo I just created and when I press "SetPrivateConfigurationRepository", I've got: 

::1 - - [20/Jun/2018:10:20:59 -0700] "POST /onboarding_erb/git_repo HTTP/1.1" 500 1208275 2.3422
2018-06-20 10:26:15 - Octokit::UnprocessableEntity - POST https://api.github.com/user/repos: 422 - Repository creation failed.
Error summary:
  resource: Repository
  code: custom
  field: name
  message: name already exists on this account // See: https://developer.github.com/v3/repos/#create:
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:28:in `post'
	/Users/bogdanbr/ci/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/client/repositories.rb:160:in `create_repository'
	/Users/bogdanbr/ci/app/services/configuration_repository_service.rb:94:in `block in create_private_remote_configuration_repo'
	/Users/bogdanbr/ci/app/shared/github_handler.rb:82:in `github_action'
	/Users/bogdanbr/ci/app/services/configuration_repository_service.rb:92:in `create_private_remote_configuration_repo'
	/Users/bogdanbr/ci/app/services/configuration_repository_service.rb:39:in `setup_private_configuration_repo'
	/Users/bogdanbr/ci/app/features/onboarding/onboarding_controller.rb:184:in `block in <class:OnboardingController>'

**Comment by nakhbari** [comment]
@KrauseFx Do we still have that issue where we only try to create a config repo and not allowing re-using an existing one?

**Comment by KrauseFx** [comment]
Mh not that I know of, let's use this one to keep track of it.

**Comment by Aravindios** [comment]
I to have same issue
 while running  FASTLANE_CI_ERB_CLIENT=1 bundle exec rackup

I get like this 

/Users/apple/.rvm/gems/ruby-2.3.5/gems/octokit-4.9.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user/emails: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)


how to solve it

**Comment by KrauseFx** [comment]
Hey @Aravindios, this project is not ready for production yet, also please be respectful and stop downvoting our comments. Your issue is not at all related to the issue you posted your comment in.

**Comment by Aravindios** [comment]
ok @KrauseFx sorry.
