### ISSUE TITLE
Replace `git reset --hard` with also resetting uncommitted files

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#103]

**Comment by minuscorp** [comment]
Is `git clean -fd` what are you looking for? This removes all untracked files and directories. Can be done just after `git reset --hard`. May I propose a PR covering this?

**Comment by taquitos** [comment]
Of course @minuscorp !
Check out our contribution guide :)
https://github.com/fastlane/ci/blob/master/CONTRIBUTING.md

**Comment by minuscorp** [comment]
Check #116 out!
