### ISSUE TITLE
File serving endpoints broken while running Build

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#1031]
While builds are running any File serving endpoint will return a `404`

It looks like during the build we change the working directory to something like `"/Users/nakhbari/.fastlane/ci/13c7965a-2911-4773-ba6c-e252e6ce5b7b/builds/0615a176d28cd4458d442090f0f21fdfd0ee22df"` so when we try to serve the HTML files, the directory is incorrect and the file cannot be found.

I think only the thread which is running the build needs to change to the build folder, not sure why our main server thread is also changing. @KrauseFx do you know where we might be changing working directories?

**Comment by KrauseFx** [comment]
I don't fully understand the 404 error and when you'll receive it. As part of which API / web socket do you get a 404 error? Does it happen when accessing the artifacts?

**Comment by nakhbari** [comment]
When loading the web client we send the files for the JS code + HTML bundle + assets. These files are sent here: https://github.com/fastlane/ci/blob/master/fastlane_app.rb#L68. The file path we use is relative. I noticed when debugging that when a build is in progress, the working directory is not `.../ci` but it's the build folder where the cloned repo is for the build. So when the endpoint tries to send the web app bundle with that relative path, it cannot find them and sends a `404`.

**Comment by KrauseFx** [comment]
Got it, this might be related to how we currently deal with git, due to some issues with the libraries we're using (@taquitos is working on patching this)

Just to confirm, the way to reproduce this is to run a build using the new frontend, and while the build is running, refresh the page, and not getting the HTML file?

**Comment by nakhbari** [comment]
Yes, this can also be reproduced in the ERB client as well.

**Comment by KrauseFx** [comment]
Got it, looking into this now. Thanks

**Comment by KrauseFx** [comment]
<img width="1200" alt="screen shot 2018-06-26 at 2 58 28 pm" src="https://user-images.githubusercontent.com/869950/41933282-6709612e-7951-11e8-88dc-9a394fe933c3.png">

So I can't reproduce this using the ERB client, will give it a try using the Angular client after the meeting
