### ISSUE TITLE
Queuing system for all work 

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#104]
- [x] Generic interface for a unit of `work`
- [x] Queue that can scale from 1 worker to multiple
- [x] Queue status reporting (number of items)
- [x] How many workers are busy
- [x] How many tasks are in the queue
- [x] How many workers are free
- [x] Queue persistence for recovery

**Comment by AndrewMcBurney** [comment]
I'd be interested in working on the Queue persistence item. 🙂 

@taquitos, you said earlier you wanted to minimize dependencies in the project. Would you like me to use a ruby-native database module such as [DBM](https://ruby-doc.org/stdlib-1.9.3/libdoc/dbm/rdoc/DBM.html)? It's a wrapper for an on-disk Unix-style Database Management Library which uses key-value data stores instead of tables and columns.

```ruby
db = DBM.open("#{file_name}", 0666, DBM::WRCREAT)

# Persisting data
db["key"] = value

# Fetching data
value = db["key"]

# Closing the database
db.close
```

**Comment by taquitos** [comment]
As a V1, I would say let's stick to a simple json file. I really like how it's human readable, and totally system-independent  (DBM has some serious `cautions` about using it). 
Also, as the first version of persistence, the real use case is more of a ledger, we want to know what tasks were enqueued and which finished.
That way, when something bad happens, we can use the current queue state as a way to figure out what went wrong.
Eventually, we should be able to re-enque, so the persistence should be able to store enough information about the task (which project was being built). This is tricky 😄 

If the interface to the storage were built in such a way as to allow multiple different persistence layers, I would totally be 💯 OK with that 🚀

**Comment by minuscorp** [comment]
I've been digging too and I found [this]( https://github.com/collectiveidea/delayed_job/blob/master/README.md), which in the section _Gory Details_ describe how they persist the tasks (they use ActiveRecord for this) but I think it's easy to have their schema as a base to work on (the model) and this can be easily implemented using JSON as the first data source.

**Comment by taquitos** [comment]
@minuscorp that's a great point, why reinvent the wheel when we have a working schema we can potentially use 🚀

**Comment by minuscorp** [comment]
Progress in https://github.com/fastlane/TaskQueue/pull/5
