### ISSUE TITLE
Websocket Logs are backfilled

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#1041]
The websocket should send all the logs up until that point on a new connection. This includes the scenario where the build is complete, we should send all the logs.

**Comment by KrauseFx** [comment]
Ha, yeah I forgot to implement this in the new JSON controller. The way we implemented it in the non-JSON controller is not by using a socket connection, but just the regular API

More info here https://github.com/fastlane/ci/blob/111cdc06add3ce501ff73f4a83bd5bd0caacae4b/app/features/build/build_controller.rb#L85-L100

When it comes to fetching the previous output, this is blocked by the distributed worker work, as we'll need to know how it's being stored

**Comment by nakhbari** [comment]
Yeah i think i'm gonna copy the current implementation for now. 

I think for the worker it would make sense to always use the websocket and just backfill the logs that have been missed on a new connection. With the last line being an EOT we will close the websocket.

**Comment by nakhbari** [comment]
@snatchev do you think this fits as a part of the distributed builds?

**Comment by snatchev** [comment]
Yup, it's mostly working at the moment on my branch
https://github.com/fastlane/ci/pull/951

**Comment by snatchev** [comment]
This feature is live in #1093
