### ISSUE TITLE
No GitHub

### ISSUE THREAD

**Issue by LivioGama** [fastlane/ci#1046]
Hello,

The documentation says : "Adapters: Store your configuration and artifacts on services you already use, like GitHub or your own git server"

What if we don't use GitHub at all ? In the onboarding when can't skip the steps related to GitHub and if we don't have an account we can't proceed further at this step.

![screen shot 2018-06-28 at 10 25 41](https://user-images.githubusercontent.com/6930498/42022449-a8f88458-7abd-11e8-8e0a-3cd1a9180c00.png)

**Comment by KrauseFx** [comment]
Right now we only support GitHub, there will be support for more code hosting services later after the first 1.0 launch 👍

**Comment by KrauseFx** [comment]
Thanks, yes it's mentioned in our goals for now https://github.com/fastlane/ci/blob/master/VISION.md#goals-for-the-initial-release

**Comment by LivioGama** [comment]
I meant that for now, it’s only github
