### ISSUE TITLE
Unable to add new projects: Invalid Lane Name

### ISSUE THREAD

**Issue by anshulagl** [fastlane/ci#1052]
Adding a new project, and selecting a lane to build on adds an extra string "no platform". When the build is triggered, the lane name is sent as "no platform <actual lane name>", which counts as an invalid lane name, and thus the build fails.

<img width="1622" alt="screen shot 2018-07-02 at 3 07 48 pm" src="https://user-images.githubusercontent.com/2488091/42188672-d2618688-7e09-11e8-82d0-5009c6922f34.png">

**Comment by KrauseFx** [comment]
Added the right milestone + label 👍

**Comment by KrauseFx** [comment]
Is that something you're looking into?

**Comment by anshulagl** [comment]
I think I need to be added in the org. I do not have access to assign this to myself

**Comment by nakhbari** [comment]
I think we just need to make `no_platform` to an empty string here: https://github.com/fastlane/ci/blob/690330a3027402c70559843f827a51cf6f81ff02/app/features-json/repos_json_controller.rb#L94

**Comment by anshulagl** [comment]
It seems that we are passing the lane and platform name in the APIs and code as space separated string. Should we just make it 2 different params, and display in the frontend as we want? Would be more flexible and will create generic APIs.

https://github.com/fastlane/ci/blob/690330a3027402c70559843f827a51cf6f81ff02/app/features-json/project_json_controller.rb#L37

**Comment by anshulagl** [comment]
The manual builds got fixed automatically with https://github.com/fastlane/ci/pull/951. Will debug to make sure we find exact cause in old build system.
