### ISSUE TITLE
 fastlane.ci: command not found

### ISSUE THREAD

**Issue by Aravindios** [fastlane/ci#1065]
**how to run fast lane.ci in Mac OS**
error while running Fastlane.ci

**apple$ fastlane.ci
-bash: fastlane.ci: command not found**
 can any one slove this.

**Comment by KrauseFx** [comment]
Did you follow the instructions provided in the main README? https://github.com/fastlane/ci#using-fastlaneci

There is no binary called `fastlane.ci` 👍
