### ISSUE TITLE
Think about security threat model for the GH API token more

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#1078]
If we build external PRs, a malicious actor can submit a PR to a repo which replaces the test scripts to just print out all ENV variables, and therefore get access to secrets like the GitHub API token

1. We can build only PRs from local branches
1. The GH token has such limited access, that it can only set the build status

Other approaches?

**Comment by KrauseFx** [comment]
Also described here
```
Pretty much every major open source project out there (at least in the JavaScript/Node community) will have automated CI that runs on pull requests.

This CI is just there to run your tests, and it provides a nice feedback loop to contributors, but since it runs automatically the second a pull request is opened, you need to be careful what that CI process has access to.

Many users of npm (including lots of major open source projects) chose to use Continuous Deployment systems to automatically publish new versions of their npm packages as things get merged into their master branch. Most of the time, this is done in the same CI system as tests.

In order to publish to npm, you need to have a "token" (something to tell npm that you are authenticated). And in order to publish to npm automatically in CI, you need to put this token into your environment variables.

Most of the time, people configure these environment variables in such a way that both your "master" build and your "pull request/branch" build get the same environment variables.

This means that simply by opening a pull request into the right repo, you can gain authorization to publish packages.

Cool.
```
via https://jamie.build/how-to-build-an-npm-worm

**Comment by nakhbari** [comment]
This is a tough one. Running local branches seems like a huge limitation on what is tested. This could be avoided by using the master Fastfile at all times, but this has its own cons.

**Comment by KrauseFx** [comment]
Running just local branches instead of external PRs for open source projects is the most common setup across the available CI systems (e.g. Travis and Circle), however I'd love to find a better solution

**Comment by KrauseFx** [comment]
Aaaaand, the next one got affected https://medium.com/@vesirin/how-i-gained-commit-access-to-homebrew-in-30-minutes-2ae314df03ab
