### ISSUE TITLE
update websocket client for builds.

### ISSUE THREAD

**Issue by snatchev** [fastlane/ci#1089]
Unblocks: #1071

Update the frontend websocket request and response handlers. Because we don't want to support two code paths, based on what kind of BuildRunner is performing the action, lets just migrate all BuildRunner invocations to `RemoteRunner`

- [x] websocket request must use authentication to establish the connection
- [x] websocket request should use the new URL, which is not a rack middleware.
- [x] must change the response handling. websocket responses are now JSON-encoded messages of type: https://github.com/fastlane/ci/blob/master/protos/agent.proto#L54
- [x] migrate existing `FastlaneBuildRunner` to `RemoteRunner`.

**Comment by KrauseFx** [comment]
What milestone should this be of? Beta?

**Comment by snatchev** [comment]
@KrauseFx yes. Milestone added.
