### ISSUE TITLE
Describe in readme how I can run the CI on my machine

### ISSUE THREAD

**Issue by castus** [fastlane/ci#119]
README's section `Development installation` has not enough information to run the service. I was trying to run the ci, but it turns out that I need:
* `FASTLANE_CI_ENCRYPTION_KEY`
* then `FASTLANE_CI_USER` and `FASTLANE_CI_PASSWORD`
* then `FASTLANE_CI_REPO_URL`
* then `FASTLANE_CI_INITIAL_CLONE_EMAIL` and `FASTLANE_CI_INITIAL_CLONE_API_TOKEN`

What are those env variables? What should I set?

**Comment by KrauseFx** [comment]
Thanks, I'll add this information to the README 👍
