### ISSUE TITLE
System requirements detection

### ISSUE THREAD

**Issue by Sherlouk** [fastlane/ci#120]
I'll start of by saying I love what you're building here and I can't wait to see it progress! 🙌 

In the same way the launch script informs the user if certain environment variables are not defined, it would be handy if the program could ensure the system meets the necessary requirements

Currently I get the following error when trying to run locally:

```
bundler: failed to load command: rackup (/usr/local/bin/rackup)
NoMethodError: undefined method `provider_credentials' for nil:NilClass
```

This is in fact caused by the fact I don't have Ruby 2.3 (or newer), an easy check to run!

Same goes for validating OS, Xcode Version, Command Line Tools and any other requirements

**Update**

Follow up work around detecting Xcode installation, and more

**Comment by taquitos** [comment]
We're super focused on getting this up and running that we haven't spent a ton of time validating that sort of thing. Is that something you'd like to help us with?

**Comment by Sherlouk** [comment]
I'm not super hot on ruby but I'll definitely give it a go!

**Comment by taquitos** [comment]
Hopefully you'll start to ❤️it 😄

**Comment by KrauseFx** [comment]
This is merged, nice work 👍

**Comment by Sherlouk** [comment]
For what it's worth, I had left it open intentionally to handle further requirements such as Xcode/what not - but we can recreate an issue when it becomes more of an issue (Ruby was throwing weird errors hence prioritised that)

Thanks though!

**Comment by KrauseFx** [comment]
Alright, good call, I re-opened, and added a placeholder for more information + context on what's required to get this card to be shipped 👍
