### ISSUE TITLE
Feature Proposal: allow for parameterized builds

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/ci#125]
Allow for parameterized builds like CLI does (`fastlane deploy submit:false build_number:24`)

### Ideas
- Allow for a textfield input or some sort of key/value input to allow similar CLI input
- Use proposed idea for formally defined lane parameters (https://github.com/fastlane/fastlane/issues/11824) to generate a UI based upon defined parameters and type

**Comment by KrauseFx** [comment]
Perfect, this will be covered as https://github.com/fastlane/ci/issues/408
