### ISSUE TITLE
Use the new `JSONConvertible` in all parts of the code 

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#137]
Refers to #110 but are more pieces of existing code that need some rewriting to conform the new `JSONConvertible` module.

**Comment by taquitos** [comment]
Do you know, offhand, which pieces of existing code need this?

**Comment by minuscorp** [comment]
https://github.com/fastlane/ci/blob/684bbf45bc4b244a021a8ffdd55f1dac1029a256/shared/models/github_provider_credential.rb#L55
https://github.com/fastlane/ci/blob/9cbaaa4c4fbe2b6bc861ef6f043df261fef45e65/services/data_sources/json_user_data_source.rb#L67
https://github.com/fastlane/ci/blob/a8c401c55a246686b82996f29b662de591b4bfdb/services/config_data_sources/json_project_data_source.rb#L80
And all relates to #166

**Comment by taquitos** [comment]
@minuscorp I think you might have updated all these, are we missing anything else?

**Comment by minuscorp** [comment]
I think it's time to close it 😃

**Comment by taquitos** [comment]
🎉
