### ISSUE TITLE
[Add new project] Views and Controllers.

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#141]
This part of the [Add new project] workflow covers the templates and endpoints needed in order to create a new project. (UI + Server)

**Comment by taquitos** [comment]
Related to https://github.com/fastlane/ci/issues/162

**Comment by taquitos** [comment]
@minuscorp this is done, right?

**Comment by minuscorp** [comment]
Yup, and the rework incoming on #283

**Comment by taquitos** [comment]
🎉
