### ISSUE TITLE
Feature Proposal - Notification Event Receivers and Dispatchable Event Actions

### ISSUE THREAD

**Issue by AndrewMcBurney** [fastlane/ci#143]
## Event Receivers and Event Actions Proposal

I have a proposal for creating project-specific event receivers and dispatchers. Users may configure their projects to dispatch event actions based on business logic they define.

This would ideally be an extension of the Notifications Dashboard (https://github.com/fastlane/ci/pull/142) and would be configurable on a project-basis through the Notifications Dashboard UI.

The `EventReceiver` and `EventAction` metadata would be configurable settings persisted to the `projects.json` file.

This proposal relates to issues https://github.com/fastlane/ci/issues/84, and https://github.com/fastlane/ci/issues/71.

### `EventReceiver`

The `EventReceiver` is an abstract base class which registers `event_actions` to be dispatched once a certain "trigger condition" is met.

It uses the [template design pattern](https://sourcemaking.com/design_patterns/template_method) to allow concretions to specify the template method `trigger_condition_met?`, letting concretions specify the logic for when events should be dispatched.

**Abstract Class**

```ruby
# Abstract class for registering events to be dispatched when some trigger
# condition is met
#
# Associations:
#   - belongs_to :project
#   - has_many :event_actions
#
# @abstract
class EventReceiver
  # @return [Array[EventAction]]
  attr_reader :event_actions

  def initialize(*)
    @event_actions = # load event actions from some persistent data store
  end

  # Registers an event with the `EventReceiver` class
  #
  # @param  [EventAction] event_action
  # @return [nil]
  def register_event_action!(event_action)
    @event_actions << event_action
  end

  # Pure virtual method template method, overridden by derived concretions
  #
  # @abstract
  # @param  [Notification]
  # @return [Boolean]
  def trigger_condition_met?(notification)
    raise NotImplementedError, "EventReceiver::trigger_condition_met? is a pure virtual method."
  end

  # Run each of the event actions corresponding to the job, if the trigger
  # condition has been met. This event will be called each time a notification
  # for a project is created, or updated
  #
  # @param  [Notification]
  # @return [nil]
  def dispatch_events_if_condition_met!(notification)
    return unless trigger_condition_met?(notification)
    event_actions.each(&:run!)
  end
end
```

**Concretion Examples**

```ruby
# Allows users to specify a regex for a notification message
class NotificationRegexReceiver < EventReceiver
  def initialize(regex)
    @regex = regex
    super
  end

  # Returns `true` if the regex receiver matches
  #
  # @return [Boolean]
  def trigger_condition_met?(notification)
    notification.message =~ Regexp.new(regex)
  end

  private

  # Regex to match notification message on
  #
  # @return [String]
  attr_reader :regex
end

# Allows users to dispatch events when some high priority notification is sent
class HighPriorityNotificatonReceiver < EventReceiver
  def initialize(priority)
    @priority = priority
  end

  # Returns `true` if the notification priority matches the priority set in the
  # receiver
  #
  # @return [Boolean]
  def trigger_condition_met?(notification)
    notification.priority == priority
  end

  private

  # The priority you're watching for
  #
  # @return [String]
  attr_reader :priority
end

# ...
```

### `EventAction`

The `EventAction` would use the [command design pattern](https://sourcemaking.com/design_patterns/command) to encapsulate a [worker job](https://github.com/fastlane/ci/blob/master/workers/worker_base.rb) to be enqueued and executed asynchronously once dispatched by the `EventReceiver`.

**Abstract Class**

```ruby
# Associations:
#   - belongs_to :event_receiver
#
# @abstract
class EventAction
  def initialize(*)
  end

  # Spawns some sort of worker job which is enqueued in a event_action task queue
  #
  # @abstract
  # @return [nil]
  def run!
    raise NotImplementedError, "EventAction::run! is a pure virtual method."
  end
end
```

**Concretion Examples**

```ruby
class EnqueAndRunLastBuild < EventAction
  # enqueue the last CI build job in the task queue and rerun
end

class SlackNotification < EventAction
  # post warning message in slack channel user can configure
end

class EmailNotification < EventAction
  # send email notification
end

# ...
```

### Benefits

- Would allow users to conditionally specify when they want their builds to retry
- Easily extensible to set up new `EventActions` (delayed emails, etc.)
- A way to have alerting built-in (notification alerts via slack, emails, etc.)

### Discussion

I was thinking we could potentially extend this to have matchers for build status codes, or `stdout`/`stderr` - to allow users to conditionally execute other builds, send alert messages, etc., based on build execution in addition to notifications.

Do you think this is a worthwhile system to implement? If so, I'd love to take a stab at it, create a PR, and get some feedback.

Thoughts? :slightly_smiling_face:

**Comment by KrauseFx** [comment]
Hey @AndrewMcBurney, thanks for taking the time to write this proposal. It sounds like a useful feature - however it's already very advanced & sophisticated. We're currently trying to limit everything to build the first MVP, to release the first beta build publicly. Let's try to focus on starting using fastlane.ci for fastlane.ci and then add support for iOS & Android 👍

**Comment by AndrewMcBurney** [comment]
Sounds good to me! 🙂 Would you like me to close the issue?

**Comment by KrauseFx** [comment]
Thanks for understanding. Maybe we should create a label for `backlog` or `after-v1`, close the issue, and then we can easily query those? The proposal is great. What do you think (and @taquitos)

**Comment by taquitos** [comment]
💯 After-MVP would be perfect. This is a great proposal.
