### ISSUE TITLE
[Proposal] Build standalone JS class to convert fastlane output from generic format to prettified HTML

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#147]
So I'm thinking a bit more about how we render the real-time log of fastlane.ci in the user's browser. We haven't decided on front-end frameworks and stuff yet, so things are still in the open
but having HTML based output for fastlane output is something that would be interesting outside of fastlane.ci also
What I mean, imagine you can run `fastlane beta --html` (a regular lane) and it would additionally generate a HTML file with colored output, which can then be used for other CI systems, etc.

so the way we could architect is could be that it's a single `.js` file that converts JSON data to beautiful HTML based log files. The JSON data could look something like this

```json
[
  {
      "type": "message",
      "text": "fastlane is great"
  },
  {
      "type": "header",
      "text": "Step: ensure_git_status"
  },
  {
      "type": "error",
      "text": "Ugh, git isn't clean"
  }
]
```

generating HTML + CSS to something like this (very simplified of course)

```html
<p>fastlane is great</p>
<h1>Step: ensure_git_status</h1>
<p class="error">Ugh, git isn't clean</p>
```

by having a single `.js` file, we could use it for existing `fastlane` setups by just running that `js` file after running a full build
and then we could use the same `.js` file for real-time output rendering for `fastlane.ci`

- So in the case of `fastlane` it would run on the user's machine locally using the local JS engine that's pre-installed on the Mac
- In the case of `fastlane.ci` we'd run it on the user's browser, piping over the JSON metadata through a web socket, updating the HTML dom for the user in real-time

**Comment by revolter** [comment]
Firstly, I don't think there is a JS engine pre-installed in macOS.
And secondly, where would the CSS be? Or we require the user to provide one, being able to customize it how they want?

**Comment by KrauseFx** [comment]
The CSS would be at 2 locations:
- for `fastlane.ci` it would be part of `fastlane.ci`
- for `fastlane` it would be bundled in the HTML file, probably a more basic style sheet

**Comment by KrauseFx** [comment]
I'm gonna have to look into more detail on the JavaScript side of things, but it looks like it's pre-installed on every Mac
```
/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc
```

**Comment by revolter** [comment]
Oh, ok, didn't know about that

**Comment by KrauseFx** [comment]
I'm of course also open for other suggestion. I guess the best alternative would be a Ruby based implementation:

- A ruby method that takes a message object (see sample JSON above) and returns an HTML formatted string
- This way it can be used directly within _fastlane_ without a dependency to JS
- This way it can be easily be used by `fastlane.ci` by piping over the direct HTML via a socket connection

**Comment by KrauseFx** [comment]
Yah I think the Ruby implementation makes more sense, will do that. Thanks @revolter 👍

**Comment by KrauseFx** [comment]
> So, this takes a fair amount of thinking about, especially due to memory usage on browsers, and handling of both long, and _wide_ logs.
> The way that many CI providers handle this is by streaming logs from the worker to the log processor (in this case probably fastlane ci main process, but this will be a memory issue). The log processor will then do two things: build a buffer of the entire log (in something like redis), and stream log lines to streaming browsers.
> When the build is completed, the full log buffer is then moved to persistent storage, and served as a file for future display in builds and downloading.
> If the log is above y chars, then save a truncated browser version, and a full downloadable version.
> So there are actually two ways that you load logs: The live log from streaming, and the full log when viewing an old build.
> You can also pre-render the log as html, as a browser optimisation.
> Many browsers have issues with rendering large logs, and will completely lock up under many circumstances. (which is where truncation comes into play)

**Comment by KrauseFx** [comment]
Update: We decided to not generate HTML on the server, but instead do it using JavaScript

**Comment by KrauseFx** [comment]
cc @taquitos

**Comment by KrauseFx** [comment]
Follow-up work via https://github.com/fastlane/ci/issues/213

**Comment by KrauseFx** [comment]
Let's close this, as it's covered by other issues
