### ISSUE TITLE
[Proposal] Use grpc for adding support for multiple fastlane.ci workers

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#149]
[grpc](https://grpc.io/) is open source, and allows us to have an efficient communication layer for our plans to scale fastlane.ci. Right now we assume everything runs on one Mac host, but of course, we want setups to have multiple workers taking on tasks, and reporting the output back to the main machine.

**Comment by minuscorp** [comment]
I'd like to put on the table another tool that I've used in high performance and high availability distributed systems, Celery. Written in Python it has some documentation about its building blocks as seen in [here](http://docs.celeryproject.org/en/latest/internals/index.html). 
Special attention to the [worker](http://docs.celeryproject.org/en/latest/internals/worker.html) and the [protocol](http://docs.celeryproject.org/en/latest/internals/protocol.html) they use.

**Comment by KrauseFx** [comment]
Alright, took a little closer look into this. If we use this to transfer the output in real time from a worker to a host, we might as well use the same technology to stream the output from the worker to the user's browsers, there seems to be some open source projects that do that (e.g. https://github.com/improbable-eng/grpc-web)

**Comment by taquitos** [comment]
Good stuff here, I think it's a really great solution to a lot of problems. What do you think about holding off on building this out until we do our first release?

**Comment by KrauseFx** [comment]
Yep, I'll try to implement a more basic version first, using bare web sockets, and then we can iterate again at a later stage of the project

**Comment by KrauseFx** [comment]
Beautiful, so we can close this for now 👍
