### ISSUE TITLE
[GitRepo] git.branches.remote returning `HEAD ->` branches

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#150]
I've digging into the reason of the branches starting with `HEAD ->`. This is something is being raised by how the `git` gem retrieves the remote branches, which IMHO, is pretty weird. We might want to extend that gem to retrieve only _true_ remote tags which can be easily attained using `git ls-remote --heads` which consists of a list of pairs `<sha> refs/heads/<branch-name>`. I think that is the actual clean list of remote branches names, or `git branch -r` which is the raw list of `<remote>/<branch-name>`. What do you guys think?

**Comment by taquitos** [comment]
It might make sense to fork the gem under the fastlane org. Since fastlane.ci heavily depends on git, it would also make sense for us to have control over it. So there is definitely an opportunity to fork and extend it to match what we need.

**Comment by minuscorp** [comment]
I'm totally into that approach, I think it'd be great to have all the `git` operations under our control.

**Comment by KrauseFx** [comment]
Forking + maintaining a fork is annoying. If we can have a 1-3 line "workaround" by excluding the branch in our code base, it would make our life a lot easier long term. Thoughts?

**Comment by taquitos** [comment]
I anticipate we'll need to continue to tweak the git gem. It hasn't been updated in 2 years, so I don't think maintaining will be bad 😄 

I think tweaking in our code, or providing workarounds isn't the right thing. IMO we should fix the source when we can either by submitting patches or forking. Adding in specific tweaks for packages will get annoying in the long run and might be deprecated by future updates to the gems.

**Comment by KrauseFx** [comment]
Let's close this for now, and re-open if we have any direct action items for this 👍
