### ISSUE TITLE
[use case] Add a project

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#162]
- [x] Add new project which only allows manual trigger
- [x] Add commit trigger
- [ ] Add new project which only allows a `release` style trigger (no manual, only commit)
- [ ] Add project with specific branch

**Comment by minuscorp** [comment]
How do we store the information about the triggers of a certain protect?
Can a project have several triggers?

**Comment by taquitos** [comment]
I added this: https://github.com/fastlane/ci/commit/a8c401c55a246686b82996f29b662de591b4bfdb
My thinking is this:
A project can have multiple triggers. Each trigger can have a different branch.
Here are the 3 types I think we should focus on: `manual`, `commit`, and `nightly`

**manual:**
if a project doesn't have a `manual` trigger, that means you can't manually trigger it. 
Why would you not want to be able to manually trigger?
  - This behavior allows for people to only be able to trigger releases when a release branch is merged after review, but not before.

**commit**
When a given branch is committed to, the project will be triggered with the trigger's specific `branch`

**nightly**
Triggered once, daily, at a specified hour and minute with the trigger's specific `branch`

**Comment by taquitos** [comment]
use case for only manual trigger: https://github.com/fastlane/ci/blob/master/docs/use_cases/add_project_manual_trigger.md

**Comment by KrauseFx** [comment]
I just realized I wrote https://github.com/fastlane/ci/pull/177 with the PR status in mind. I have to say I don't know enough about how GitHub handles things but from what I understand, the `Build PRs` would basically be the same as `commit`, with the exceptions of not building commits from random branches, until there is a PR. This allows larger teams to optimize their use of CI resources by not submitting a PR yet I guess, but thinking about it now, it might make sense to change/rename that to just `commit` based, and have the web UI mention that this is what you usually want to use if you want test statuses for PR (as a PR test status really is just the test status of the most recent commit of a given branch)

**Comment by nakhbari** [comment]
Is `Project` the industry standard name for these build configurations?
Is there a use case where a user would have 2 Projects with the same repo and lane?

**Comment by taquitos** [comment]
There aren't really any industry standards around naming stuff for CI. Each CI system implements their structure differently, some have `workflows` others have `projects`, and some have `jobs`, they also implement various hierarchies. In our case, projects are meant to be `repo` + `lane` + `trigger` + `builds`. This way people can chose to customize their setup however they want. 
One observation we've had is that CI setups are always very custom, and if you force a certain flow, it works for some, but others hate it. 
So, yeah, developers can have 2 projects with the same `repo` and `lane`, they can have different `triggers`, they can be on different `branches` of the repo, or they can be exactly the same setup.

**Comment by taquitos** [comment]
From our slack convo:

When I use CI, I have about 3 projects I care about, and those 3 projects are associated with 1 repo
so, having the repo be top-level is more of a hassle, especially because I name my jobs like this:
`My App Commit Tests`, `My App TestFlight Deploy`, and `My App Screenshot`. What would be more valuable to me is a list of all my projects (generally under 10 projects), and a search box that allows rapid filtering

The key is that we’re really focused on mobile-first, and medium-sized teams (5 to 25 people) which only seem to have 1 or 2 products which come from the same repo, or maybe a second repo. So in practice, you'd be left with extra hierarchy to click though with very little organization benefit.

**Comment by taquitos** [comment]
Add new project which only allows a release style trigger (no manual, only commit) #455

**Comment by taquitos** [comment]
Add project with specific branch #456
