### ISSUE TITLE
[use case] Delete fastlane.ci user

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#164]

**Comment by KrauseFx** [comment]
Should this be tagged as `after-mvp`? Because once a GitHub user gets removed from an organisation, they don't have access using fastlane.ci anyway, right?

**Comment by taquitos** [comment]
That's a good question.
before displaying the dashboard, we should check the user's permissions with github, and in that case, they would see 0 projects. I like this.

**Comment by taquitos** [comment]
So basically, if somebody's access gets revoked on github, that person's dashboard should reflect those changes without having to logout and back in
It would be good to have a use case covering this specific part.

**Comment by KrauseFx** [comment]
> that person's dashboard should reflect those changes without having to logout and back in

Yes, I think that should be the case for everything, no matter if you're removed from an org, removed from a repo, or a repo is added/removed from the fastlane.ci config. For now we currently just fetch the projects every time I think, long term, we could cache the repos the user has access to during the login/register, and then refresh that in a low priority background task every hour or so?

**Comment by minuscorp** [comment]
So, for now this is done within the `/dashboard` load:

https://github.com/fastlane/ci/blob/de31033c66371c5f26fd9f42d961e3d684fe75f7/services/config_service.rb#L52-L60

Using the `ConfigService` and the current `ProviderCredential`. So this is updated each time the page is refreshed

**Comment by taquitos** [comment]
So this is great!
Then I think the last step here is to capture what a fastlane.ci user will actually experience when they use the system.

**Comment by minuscorp** [comment]
I think it is great that the access to a certain project (and its repo) is retrieved on demand on the `/dashboard` load. I think the main issue an user can face is what happens when it tries to load a project that no longer has access (but he sees it on the dashboard because he hasn't refreshed) on every `/project/*` call, we should check the access too, so we can redirect to the refreshed `/dashboard` with the appropiate notification.

**Comment by taquitos** [comment]
Delete fastlane.ci user #454
