### ISSUE TITLE
[use case] Manually trigger build

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#165]
How do we want to trigger a manual build? From where?

**Comment by minuscorp** [comment]
This is something that you can already do (but for now it does nothing yet), in the project details view, trigger a build.

**Comment by taquitos** [comment]
Yup, we certainly have the ability to do this, but this is more about specifying exactly what the user expects to do. We haven't decided exactly how things should look yet, so if we specify how a user wants to interact with the system, that can inform future design works.

I expect a few different ways of triggering builds. Project page, maybe from the dashboard list of projects, maybe you can trigger a build using a different branch? Maybe you can trigger a build from a build failure notification.

I'm hoping we can write out use cases for all the ways we expect the user to want to interact with fastlane.ci

**Comment by KrauseFx** [comment]
The story is already complete and in `master`, can we close it?
