### ISSUE TITLE
JSONConvertible support properties that are arrays of objects

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#166]
Support unmarshalling of objects that have arrays of objects as a property
For example:
https://github.com/fastlane/ci/blob/master/shared/models/project.rb#L23
- [ ] Update JSONConvertible
- [ ] Update `json_project_data_source.rb` for nested objects in `project.rb`
- [ ] Update `json_user_data_source.rb` for nested objects in `user.rb`

**Comment by minuscorp** [comment]
I can tackle this, as I have rewritten some part of it and I'm familiar on how it works. As `Array` in Ruby aren't strongly typed I thought that this could be done with (yet another) mapping. We currently have `property_type_map`, when the type is `Array` we can check the `property_is_array_of_type_map` to find the property and its type, if no type is found, we use the standard `.to_s` encoder.

**Comment by taquitos** [comment]
I bet you could use the same `property_type_map` and just check to see if the json object's property is an Array, and then map it.

**Comment by minuscorp** [comment]
I can know that it is an array, but which type holds inside of it?🤔

**Comment by taquitos** [comment]
Since arrays can be anything, we need to add some rules.
1. If you use JSONConvertible, the Array should contain the same type of object
  - Then you can use `property_type_map` to define the type
2. If the array must contain different items, then I suggest creating a mapping at runtime by adding an explicit `map_enumerable_type` method to the mixin for the class such that:
- When it encounters something that is enumerable, we perform `map_enumerable_type` which takes the name of the enumerable property, along with a single item from the enumerable property and expects back an object. That way, when we encounter an enumerable type, we can just implement some logic to map it properly
e.g.:
```ruby
class Project
  include FastlaneCI::JSONConvertible
  def self.attribute_to_type_map
    return { :@repo_config => GitRepoConfig }
  end
  def self.map_enumerable_type(enumerable_property_name: nil, current_json_object: nil)
    if enumerable_property_name == "job_triggers"
      # JobTrigger needs a factory method that reads `json[:type]` and instantiates the proper type 
      return  FastlaneCI::JobTrigger.create(json: current_json_object)
    end
  end
end


```

**Comment by minuscorp** [comment]
Progress on #173
