### ISSUE TITLE
Support Fastfiles that have no platforms

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#171]
As introduced via failing tests via https://github.com/fastlane/fastfile-parser/commit/105b4ad94cb89a1f75f350061c2950baf5fad3ca

**Comment by KrauseFx** [comment]
test comment

**Comment by KrauseFx** [comment]
test comment

**Comment by KrauseFx** [comment]
test comment

**Comment by minuscorp** [comment]
Progress in:  https://github.com/fastlane/fastfile-parser/pull/7

**Comment by minuscorp** [comment]
Can we get this closed now? 🚀

**Comment by KrauseFx** [comment]
Yesss, thanks 👍
