### ISSUE TITLE
Implement consistent URL routes

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#208]
Implement https://github.com/fastlane/ci/pull/207/files, resulting in https://github.com/fastlane/ci/blob/master/docs/UrlRoutes.md

**Comment by minuscorp** [comment]
The part of creating resources is missing I think! It'd be useful to add it in a showing revision 😁

**Comment by jcampbell05** [comment]
@minuscorp can you elaborate ? :) I'm about to start this and I think I have an idea :)

**Comment by minuscorp** [comment]
If you take a look into `project_controller` you'll see that there is two endpoints to create a `Project` resource, it is a combination of both a get request to start the process and a post request with the final resource creation. This will happen (in a wide variety of ways) across the platform, we should try to normalize how we create resources (models), y'know, the C of CRUD 😁

**Comment by jcampbell05** [comment]
@minuscorp got it :), of course I have a few ideas. I'm thinking we use convention over configuration for this.

**Comment by minuscorp** [comment]
The easiest the better, we want people to actually know how to contribute 😂

**Comment by KrauseFx** [comment]
Alright, so @jcampbell05 is working on this card 👍

**Comment by KrauseFx** [comment]
Because we change to a front-end application, so it might not be worth investing more time for now, it's more a nice to have.

**Comment by jcampbell05** [comment]
@KrauseFx cool no worries, anything else I can do ?

**Comment by KrauseFx** [comment]
Sure thing, lots of tasks in the pipeline, we tried to list them over here for the `Beta` milestone https://github.com/fastlane/ci/milestone/14. In particular the ones with the `You can do this` label are up for grab
