### ISSUE TITLE
Interface to add triggers to a project.

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#209]
We have now different implementations of build triggers but, AFAIK, we do not provide any interface to establish at least one trigger (the manual one) in a default way (as things get moving forward, @taquitos mentioned that a manual trigger wouldn't be desired for every project), but I think for developing purposes we need an easy way to trigger builds by ourselves, specially now that we're achieving a nice _fastlane_ runner and on progress build artifacts.

**Comment by getaaron** [comment]
In case it helps, here’s a related request I opened against CircleCI: https://discuss.circleci.com/t/parameterized-manually-triggered-builds/19633

The ability to accept parameters for manually triggered builds is especially helpful.

**Comment by KrauseFx** [comment]
Yes, actually @taquitos and I chatted about this in person yesterday, and we created https://github.com/fastlane/ci/issues/408.

The goal would be to trigger a build for a specific PR or a specific branch, and maybe even provide some specific parameters (e.g. env variables)

**Comment by KrauseFx** [comment]
Let's close this in favor of https://github.com/fastlane/ci/issues/408
