### ISSUE TITLE
Generate `fastlane.verbose.log` as part of the build artifacts

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#214]
Introduced via https://github.com/fastlane/ci/pull/200
Depends on https://github.com/fastlane/ci/pull/205

Currently `fastlane.log` is generated in the local directory. We want the log file to be stored as an artifact. Also, this task should also include generating multiple log files, ideally we generate a `fastlane_build.log` and `fastlane_build_verbose.log` or similar, which includes the `UI.verbose` output 👍

**Comment by minuscorp** [comment]
Included in #205

**Comment by minuscorp** [comment]
We can close this now, as #205 was closed 😄

**Comment by KrauseFx** [comment]
@minuscorp cool, thanks. But we didn't implement the `verbose` log yet, right?

**Comment by minuscorp** [comment]
Ha, no, I mean, I create the artifact and store it with the log of the build as it's created by now

**Comment by KrauseFx** [comment]
Cool, renamed the card to mention `verbose` 👍

**Comment by minuscorp** [comment]
For me to clarify, what log is this `verbose` log? Is something attached to a build I suppose but I don't know which piece of code should generate it 🤔

**Comment by KrauseFx** [comment]
Ah, sorry, I didn't provide enough information here. _fastlane_ prints out a lot of stuff. In particular you can run _fastlane_  in verbose mode using `fastlane [lane_name] --verbose`, which will print out lots of extra information that's usually not needed. Sometimes it's extremely helpful though when you're trying to debug problems. 

Currently we don't use them at all for `fastlane.ci` (https://github.com/fastlane/ci/blob/master/features/build_runner/fastlane_build_runner_helpers/fastlane_ci_output.rb#L99). Ideally we generate 2 `fastlane.log` files, one for the default output, one for the verbose output, and store both of them for the user. Or at least make it an option for the user :) 

Let me know if that makes sense

**Comment by minuscorp** [comment]
For the same build is possible to filter some level of logging (verbose) and default logging? Should `FastlaneCIOutput` generate both logs or maybe we can hook several `FastlaneCIOutput` to _fastlane_?

https://github.com/fastlane/ci/blob/0a5c5a982a5cffeddd288d74988d16bd1fc6e20c/features/build_runner/fastlane_build_runner.rb#L48

**Comment by minuscorp** [comment]
To address this issue I've thought on the following:

- Create `FastlaneLogSeverity` as a module of constants with the different levels of severity in a log.
```ruby
module FastlaneLogSeverity
  VERBOSE = 1
  INFO = 2
  WARNING = 3
  ERROR = 4
  CRASH = 5
  # etc.
end
```
- Create `FastlaneLog` with `file_path` and `severity` properties.

- Let `FastlaneCIOutput` have `logs` (of type `Array(FastlaneLog)`) that are listeners for `row`s events for a certain `severity` level message.

- Erase the responsability of `FastlaneCIOutput` of writing the log, make it just a dispatcher of events coming from _fastlane_.

**Comment by KrauseFx** [comment]
This sounds like a great advanced and solid solution, however maybe it makes sense to start with something simpler? Like just either normal output, and verbose output? I don't see a good use-case for when you want just CRASH or ERROR output to be honest

**Comment by minuscorp** [comment]
So I can simplify the approach by just setting the `FastlaneLogSeverity` with `VERBOSE` and `NORMAL` (or `INFO`) and leave the rest as I proposed it? I can implement this in parallel with my other task, I don't think this should be complex to build with the existing codebase. What do you think?
