### ISSUE TITLE
Investigate git chdir warnings when connecting fastlane.ci with fastlane

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#215]
Introduced with https://github.com/fastlane/ci/pull/200

```
lib/git/lib.rb:460: warning: conflicting chdir during another chdir block
```

_fastlane_ makes use of `Dir.chdir` as part of executing the `Fastfile`. This is necessary as we want the `Fastfile` to run in its directory and not in the project root directory. Unfortunately, this seems to cause weird conflicts with the git library we use. From what I see, it's not possible to stop using `Dir.chdir` as part of _fastlane_, as we do want to run in a different directory. However, I don't yet understand why this causes a conflict, as we don't run `fastlane` as part of a `git` command. This will require some further investigation.

**Comment by taquitos** [comment]
Fixed!

**Comment by KrauseFx** [comment]
yesss 🚀
