### ISSUE TITLE
Refactor `TestRunnerService` to only have one instance of `TestRunnerService` that holds references to all test runners

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#216]
As seen in https://github.com/fastlane/ci/pull/200/files#diff-62e64a60028b7cd0fdf6248bbc3f9bfcR13, we currently have to store references to all active `test_runner_services` to keep them alive, and to be able to access them when the user wants to see their progress. I added a comment with a proposal on how we can properly architect it

We probably want a single instance of `TestRunnerService` (like we do for other services), that holds references to all the active `TestRunners`

**Comment by minuscorp** [comment]
Yep, I'm totally with you on this. A single `RunnerService` must live throughout the application, which holds references to each `Runner` that might be running at a given moment. One service, many runners.

**Comment by taquitos** [comment]
@KrauseFx what are the responsibilities that the new refactored `TestRunneService` will have?

**Comment by KrauseFx** [comment]
@taquitos 

So I was thinking of doing the following

### TestRunnerService
Responsible for
- Manage all `TestRunner` objects that are active (either in queue or actually running)
- Measures the time of a `TestRunner`'s execution
- Stores the `Build` information in version control and triggers the report of the build status on GitHub

### TestRunner
(e.g. `FastlaneTestRunner`) Responsible for
- Loading up _fastlane_ and running a lane with it, checking the return status
- Raise an exception if build fails, with information that can be handled by `TestRunnerService`
- Reporting back a list of artifacts  to `TestRunnerService`

Thoughts?

**Comment by taquitos** [comment]
I love it. One question, and it's a minor one, should we rename them to `BuildRunnerService` and `BuildRunner`?

**Comment by KrauseFx** [comment]
I don't feel strongly about the name `BuildRunnerService`, so that works. Any specific reason why it's not a service? I thought it behaves similarly to the other `fastlane.ci` services we already have, as in it stays alive and manages things (state :trollface:)

**Comment by taquitos** [comment]
I was just saying `TestRunnerService` -> `BuildRunnerService` and also `TestRunner` -> `BuildRunner` to align us around the `build` terminology instead of `test` and `job`.

**Comment by KrauseFx** [comment]
Ah right, sorry misunderstood your message, yeah that works 👍

**Comment by KrauseFx** [comment]
Will work on that refactor today
