### ISSUE TITLE
Migrate to React/Angular Web Framework 

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#222]
Looking into the work require to move to using a framework like React/Angular. These frameworks are single page applications in the sense that they have a root html page that is continuously modified.

Current web infrastructure:
We use *Sinatra* to serve static html web pages that have been generated through ERB. So every request we make to the current server will return a static html page that will be displayed to the user. 

Work required:
Because Angular/React are single page frameworks, there needs to be 2 servers: one that hosts the web server and one that serves data to web server.

I would imagine that this would require us to have Sinatra only return json data and then having a simple web server to host the Angular/React web app.

Pros:
- Separation of concern between Frontend and backend
- Can re-use components made by others in the community
- Frameworks help out a lot, productivity-wise
- JS/TS ❤️ 

Cons:
- Some initial work required
- Users *might* have to worry about scalability for their web and data servers instead of just one

**Comment by KrauseFx** [comment]
Adding @taquitos to this also. Background information: In the beginning we decided to server HTML vs JSON to speed up the initial development process

**Comment by taquitos** [comment]
I think we should continue to explore single page webapps, but still go full steam ahead with our current design for MVP. Remembering that the M in MVP is Minimum 😄
It would be trivial to migrate off ERBs and into a single-page webapp. I just don't want to do that right now because then we'd be committing to building a client on top of the server, and having to handle all the complexities that come along with that.

**Comment by nakhbari** [comment]
@taquitos I agree. Though I think developing in a single page webapp would be significantly faster than ERBs, probably biased here since I don't know much about ERBs.

**Comment by taquitos** [comment]
ERBs are just server-side html templates. Sprinkle some variables here and there, then call a method to generate the html, and then viola!

**Comment by KrauseFx** [comment]
Alright, we decided this is the direction we want to go in, so a result, let's create smaller PRs/Issues as a result for the specific features and views 👍
