### ISSUE TITLE
Get fastlane to execute project's Fastfile in project's scope

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#225]
This is a follow up from #205 where I raised the issue for the first time but I open this card to tackle the issue in other PR.

This is the recap:

https://github.com/fastlane/ci/blob/658b171d257f9c938a9089b0d8c2341910253783/features/test_runner/fastlane_test_runner.rb#L46

Where we load the fastfile of the (presumably) project we're building on. If we debug that line, we get that `FastlaneCore::FastlaneFolder.fastfile_path` evaluates to (for example): `~/Documents/ci/fastlane/Fastfile`. The local folder of the CI itself, instead of the Fastfile of the project we're building. For this reason, every action executed by the fastfile.runner is the scope of the CI, instead of the project local path. This is why _fastlane_ does not find the _xcodeproj_ or other files needed for the action execution.

UPDATE-1: I did `Dir.chdir` to the `project.repo_local_path` and `FastlaneCore::FastlaneFolder.fastfile_path` correctly evaluates to the Fastfile of the project. But when executing the runner, it fails, it returns to the current executing directory, raising:

`#<FastlaneCore::Interface::FastlaneError: Project file not found at path '/Users/me/.fastlane/ci/fastlane-ci-demoapp.xcodeproj'>`

UPDATE-2: I debugged this into the fastlane internal runner until this point.

```ruby
[13] pry(#<Fastlane::Runner>)> path_to_use
=> "./fastlane/"
[14] pry(#<Fastlane::Runner>)> Dir.pwd
=> "/Users/me/.fastlane/ci/10fed6c0-5ed9-4630-8462-534e300d3b12"
But still #<FastlaneCore::Interface::FastlaneError: Project file not found at path '/Users/me/.fastlane/ci/fastlane-ci-demoapp.xcodeproj'>
```

**Comment by taquitos** [comment]
Done 🎉
