### ISSUE TITLE
Re-implement the `rerun` method for builds using the new architecture

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#233]
Via https://github.com/fastlane/ci/pull/230

>  Think about how we want to implement the rerun method, do we actually need it? Should we just trigger a new build instead, now that we can do that?

**Comment by KrauseFx** [comment]
test comment

**Comment by minuscorp** [comment]
As `TaskQueue` implements queue's task recover, in case of system failure or other event, I think it is safe to just run once

**Comment by KrauseFx** [comment]
I have to say, I don't know if there is any action required for this one

**Comment by KrauseFx** [comment]
It might just work now

**Comment by KrauseFx** [comment]
We decided there is no concept of `rerun` a build 👎

**Comment by KrauseFx** [comment]
You'd just trigger a new build
