### ISSUE TITLE
Manage environment variables via web UI

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#240]
As we can already manage the basic environment variables via a web UI (thanks @AndrewMcBurney 🎉), we probably don't want to store all of them in the local file `~/.fastlane/ci/.keys`, as it will not be synced between machines (e.g. new Mac), but also thinking ahead: multiple Mac workers having to access ENV variables (like the `MATCH_PASSWORD` or `FASTLANE_PASSWORD`)

<img width="500" alt="screen shot 2018-03-08 at 1 36 17 pm" src="https://user-images.githubusercontent.com/869950/37169345-b245db72-22d5-11e8-930b-bba7989ce18d.png">

The proposal is to just use the same approach to encrypt strings we already use for `users.json` and introduce a `keys.json` as part of the `ci-config` repo, that stores all secrets and ENV variables, except for the ones that are necessary to do the initial clone of the `ci-config` 👍 

I think these should be enough
- FASTLANE_CI_ENCRYPTION_KEY
- FASTLANE_CI_USER
- FASTLANE_CI_PASSWORD
- FASTLANE_CI_REPO_URL

Related code was introduced with https://github.com/fastlane/ci/pull/194

**Comment by taquitos** [comment]
@AndrewMcBurney can we close this out?

**Comment by KrauseFx** [comment]
No, that's not implemented yet, this issue is about `keys.json`, to store additional env variables within the `ci-config` repo

**Comment by KrauseFx** [comment]
Use-cases:

https://github.com/fastlane/ci/blob/master/docs/use_cases/edit_global_env_variables.md
https://github.com/fastlane/ci/blob/master/docs/use_cases/edit_project_env_variables.md

**Comment by KrauseFx** [comment]
Let's close this in favor of the 2 issues:
- https://github.com/fastlane/ci/issues/439
- https://github.com/fastlane/ci/issues/441
