### ISSUE TITLE
[Proposal] Don't ask for the user's email address, it should be available via the GitHub API using the personal access token

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#243]
^ title says it all

**Comment by taquitos** [comment]
People might want to use a different address than their github address. 
**Example:** if I were using CI at google, I'd want to use my google email, but still use my gmail address for the token.

**Counter-proposal:** pre-populate the email field with the github email and allow the user to edit it.

**Comment by KrauseFx** [comment]
Yes, good point 👍
