### ISSUE TITLE
Automatically select the lane that is chosen for the project in the UI

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#258]
When you select a lane in the project and save it, and then navigate back to the lane selection UI, it isn't selected as active. Example:

<img width="369" alt="screen shot 2018-03-09 at 8 51 40 am" src="https://user-images.githubusercontent.com/1304821/37219095-43c36e88-2377-11e8-93eb-ce9152042fc9.png">

My project is actually configured for `return_failure` lane, so that one should be selected by default.

**Comment by KrauseFx** [comment]
In general, I think something funky is going on when the user `navigates back`... it caches everything, with outdated information somehow

**Comment by KrauseFx** [comment]
Yah, we're getting a new front-end anyway 👍
