### ISSUE TITLE
Responsive layout a little too responsive

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#259]
Let's have more sane collapsing of view. This feels like it's still very wide and shouldn't have collapsed.
Collapsed: 
<img width="964" alt="screen shot 2018-03-09 at 8 55 16 am" src="https://user-images.githubusercontent.com/1304821/37219333-e8ef0fac-2377-11e8-8272-a852b2bd5cdb.png">

Uncollapsed:
<img width="1063" alt="screen shot 2018-03-09 at 8 57 47 am" src="https://user-images.githubusercontent.com/1304821/37219356-f7e982e4-2377-11e8-8644-33929477d4b6.png">

**Comment by KrauseFx** [comment]
Let's close this in favor of https://github.com/fastlane/ci/issues/222
