### ISSUE TITLE
New project flow doesn't create any job triggers

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#263]
Onboarding a new project, will cause the `Trigger build` button to crash, since no triggers are being added. Until we have the actual selection of the trigger type, let's add the basic triggers to make manual triggers to work again 👍

**Comment by minuscorp** [comment]
I'll add `ManualTrigger` by default on project creation

**Comment by minuscorp** [comment]
Relates #209

**Comment by minuscorp** [comment]
#253 Adds `ManualTrigger` by default, while development is on course.

**Comment by KrauseFx** [comment]
This is shipped now, right?
