### ISSUE TITLE
Dashboard status display not implemented yet

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#265]
<img width="504" alt="screen shot 2018-03-09 at 9 49 10 am" src="https://user-images.githubusercontent.com/1304821/37221535-3b2fcbf6-237f-11e8-8e2a-3ed5610792b6.png">

<img width="420" alt="screen shot 2018-03-09 at 9 49 14 am" src="https://user-images.githubusercontent.com/1304821/37221539-3e583444-237f-11e8-80c5-dc595cc0083a.png">

**Comment by KrauseFx** [comment]
I love how we use the 🌔 emoji 👍

**Comment by KrauseFx** [comment]
I rephrased the title, as currently we just have a static emoji there 👍

**Comment by taquitos** [comment]
🎉
