### ISSUE TITLE
syncing repo changes logic might need updating

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#282]
Looking at https://github.com/fastlane/ci/pull/277/files
`if !repo.status.changed == 0 && !repo.status.added == 0 && !repo.status.deleted == 0 && !repo.status.untracked == 0`

I think this should be `if repo.status.changed > 0 || repo.status.added > 0 ||repo.status.deleted > 0 || repo.status.untracked > 0`

If we have any changes, either changed, added, deleted, or untracked, we want to run that following logic. Am I missing something?

**Comment by minuscorp** [comment]
Totally right

**Comment by taquitos** [comment]
Ok cool, thank you for helping me understand that!

**Comment by KrauseFx** [comment]
The question, is it `you can do this`? Or is someone already working on it?

**Comment by minuscorp** [comment]
As I'm rewriting it all in #283, maybe we can keep this open
