### ISSUE TITLE
Unify fastlane.ci spelling

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#286]
Might be a little too early for now, I usually use `fastlane.ci` using backticks, but I see parts of the code base spell it as FastlaneCI. We don't have to decide now, but once we decided we should enforce things using automated checks.

**Comment by taquitos** [comment]
`fastlane.ci` is our "user friendly" string, whereas `FastlaneCI` is our `module name`
I think we should default to `fastlane.ci`. Thoughts?

**Comment by KrauseFx** [comment]
Ah right, yeah I'm ok with `fastlane.ci` as we own the domain. The module name is fine, but I saw multiple code comments where we used the same spelling, but you might be right, it was probably in the context of the module name
