### ISSUE TITLE
Containerize fastlane.ci

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#296]
It would be really nice to have a docker image or something that we could deploy. 

It's not a requirement since we expect most people to deploy directly on a Mac. This only benefits fastlane.ci running for fastlane.ci or any other project that doesn't require a Mac (for Xcode, and other build tools)

**Comment by adellibovi** [comment]
Hi @taquitos, I created a PR (#619) to address what you are mentioning.

Eventually we could push the image to the DockerHub and/or supporting for development deployment too (which in my opinion is something nice to have in the future: not having to install specific version of Ruby and gems and still be able to contribute to the project).

**Comment by taquitos** [comment]
Yey!
