### ISSUE TITLE
If commit is coming from a repo fork, also check that

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#317]
See https://github.com/fastlane/ci/pull/316 as an example
Right now we only check the current project, but we need to actually check the fork of any incoming PR.
- Can't just check for commits
- Must check for open PRs and get forks.

**Comment by minuscorp** [comment]
A fork of a PR (which target's someone else's org) is not out of the scope of a `Project`?
```
master -------------------- org1
        \--------PR ----/  org2
             \---fork--/  org2
```
