### ISSUE TITLE
Update ProjectController to include selector for branches->lanes

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#357]
Depending on the `job_triggers` and which branches they act on, we need to display a selector for that shows the lanes that are available in each branch.

Specifically to address this: https://github.com/fastlane/ci/pull/356/files/c586a78d7dc5c6bf5ced019739ea081dc0affdea#diff-0f21071ad6714e58aef92b39b939ac6fR175

**Comment by KrauseFx** [comment]
Yes, that's merged 👍
