### ISSUE TITLE
Local CI config repo

### ISSUE THREAD

**Issue by viktorasl** [fastlane/ci#393]
Maybe the proposal might be not relevant (in that case just close the issue, might be that I have a knowledge flaw):
For dev purposes I've adjusted `FastlaneCI::ConfigurationRepositoryService` to be able to work with local CI config repo if needed.

* Could a real-world purpose exist to have local CI config repo (repo in CI machine)? 
* (if previous is positive) Would we want to tackle that (maybe post MVP)?

**Comment by taquitos** [comment]
@viktorasl I think this is a legit use case, and we probably should support it along with just plain git repos (not from github)
I *think* post MVP might best.
