### ISSUE TITLE
Favor `self.var = _` over `@var = _` and attr_reader

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#400]
Using proper scopes for our attributes would be 💯. We have a better idea of what things we need access to now that CI has been moving along.
We had a PR open for this, but it got really out of sync with master so we closed it: https://github.com/fastlane/ci/pull/344

**Comment by AndrewMcBurney** [comment]
@KrauseFx, why did you unassign me from this issue?

**Comment by AndrewMcBurney** [comment]
Closed with #462
