### ISSUE TITLE
Do we deal with passwords or API tokens?

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#406]
Discussion started in https://github.com/fastlane/ci/pull/402#discussion_r177645737

My feeling is that we deal with API tokens, and should never encourage any user to provide their actual password. If that is accurate, we should reflect that in the environment variable names and config files

**Comment by taquitos** [comment]
Yeah, I think you're probably right, just API Tokens, so the field is mislabeled

**Comment by KrauseFx** [comment]
And if so, is there a way to prohibit the user from entering their password. This could be an after MVP task of course

**Comment by taquitos** [comment]
I bet github tokens are a certain length. So at the very least, we could verify the length of the tokens and if it is incorrect, we could let them know they should use the token, not a password.

**Comment by getaaron** [comment]
IIRC GitHub uses OAuth2 Bearer tokens 🐻 

https://tools.ietf.org/html/rfc6750

I don’t think there’s a guaranteed length so I’d be hesitant to include a strict length requirement to validate a token.

**Comment by taquitos** [comment]
Yeah, the length is more of a loose guide, like if it length is < 20, we can be pretty confident they entered a password and we should just point out "Hey, are you sure this is a token? If so, that's cool, continue on your way"

**Comment by KrauseFx** [comment]
Sounds like an easy win to just compare the length for now 👍

**Comment by minuscorp** [comment]
From `Octokit` README:
```ruby
client = Octokit::Client.new(:access_token => "<your 40 char token>")
```

**Comment by minuscorp** [comment]
Also, I'd recommend to migrate the `.keys` file (environment variables) into something more user-friendly (i.e., `json`, `yml`)

**Comment by KrauseFx** [comment]
Yep, so keys it is. Let's not do any changes with `.keys` for now, we can solve this together with https://github.com/fastlane/ci/blob/master/docs/use_cases/edit_project_env_variables.md

**Comment by KrauseFx** [comment]
And https://github.com/fastlane/ci/blob/master/docs/use_cases/edit_global_env_variables.md

**Comment by KrauseFx** [comment]
No idea why I closed this, we still need to implement the check to avoid people entering their actual GitHub password

**Comment by taquitos** [comment]
Done 🎉
