### ISSUE TITLE
Update URL info when adding a new project

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#411]
The URL was `http://localhost:9292/projects_erb/add/Themoji%2Fios` for me

`Themoji%2Fios` isn't perfect, it should be

`http://localhost:9292/projects_erb/add/github/Themoji/ios`
or
`http://localhost:9292/projects_erb/add?provider=github&org=Themoji&repo=ios`

The GET parameters might actually be better than the path 👍

**Comment by KrauseFx** [comment]
What do you think?

**Comment by minuscorp** [comment]
The decision was made by the ease that the `erb` lets the developer to scape the `owner/repo` string in a single parameter (scaped: `owner%2Frepo`) and later on getting it unscaped (`owner/repo`) without any backend transformation needed, sinatra just gives you what you should expect in that case. But this should be easy to change if you consider it "ugly".
I first tried: `add/github/Themoji/ios` but it didn't worked well (can't remember why, maybe sinatra wasn't interpreting the `/` as part of the URL and needed the scaping). 
This: `provider=github&org=Themoji&repo=ios` kind of breaks the _style_ that we were trying to follow with the URL schema.

**Comment by KrauseFx** [comment]
Nice 👍
