### ISSUE TITLE
[use case] Accessing build details

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#417]
- Build duration
- Build started at
- Type of trigger
- Similar issues on GitHub on failed builds
- Access to artifacts (https://github.com/fastlane/ci/blob/master/docs/use_cases/access_build_artifact.md)
- Rebuild button (if manual trigger is enabled)

**Comment by taquitos** [comment]
Similar issues on GitHub on failed builds #449

**Comment by taquitos** [comment]
Access to artifacts #450

**Comment by taquitos** [comment]
Build info page: Rebuild button (if manual trigger is enabled) #451

**Comment by KrauseFx** [comment]
We already have that https://github.com/fastlane/ci/blob/master/docs/use_cases/access_build_artifacts.md
