### ISSUE TITLE
[use case] Fastfile editing

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#422]
- Interactive lanes (can click on them to unfold and see all - attributes)
- Drag and drop to reorder and switch action nodes between lanes
- Action directory with most popular actions at top and search - filter
- Save button clearly visible 
	- CI offers to do test run on success
	- Describe change in popup for commit message (or blank)
	- Commit on developer’s behalf
- Add new lane button, after successfully adding it
	- Ask if user wants to use this lane for this project, or create a new project with a copy of the current project but with this lane?

**Comment by taquitos** [comment]
Fastfile editor #442
