### ISSUE TITLE
Dashboard search field

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#448]
Search field auto focused (search as you type)

**Comment by KrauseFx** [comment]
Yes, this is a great feature, but I feel like something we don't yet need for a successful beta release, moving this to the 1.0 milestone for now 👍

**Comment by nakhbari** [comment]
Is this to search through the projects? I didn't add this to the original task for the dashboard because i was under the impressions that the number of projects would be low. Is that not the case?

**Comment by taquitos** [comment]
We haven't spec'd it out, but potentially, it could act like how Finder does. It could search metadata along with project title so you can quickly narrow down between the number of projects you have which one is configured for what if the title isn't descriptive enough.

Probably a 1.0 thing, if that.

**Comment by KrauseFx** [comment]
Yep, or maybe even post 1.0, we can see at what point users ask for it, especially since developers are usually aware of the CMD + F shortcut 👍
