### ISSUE TITLE
Build info page: Rebuild button (if manual trigger is enabled)

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#451]
When you are in the build info page, we should be able to trigger a new build, but only if manual trigger is enabled.
- Part of this is implemented in erb.

**Comment by KrauseFx** [comment]
We can already rebuild now, but right now we always show the rebuild button, even if there is no trigger, so that's the only piece left

**Comment by taquitos** [comment]
Awesome, so we should hide the rebuild button if we don't have a `:manual`-type trigger

**Comment by KrauseFx** [comment]
I guess the actual controller implementation is small, and this is mostly a frontend task, right? cc @nakhbari

**Comment by KrauseFx** [comment]
Sounds good - maybe we can simplify it for now, and have the confirmation dialog contain a dropdown for the available branches, defaulting to the repo's default branch (usually `master`)?

**Comment by KrauseFx** [comment]
Assigning us both, I'll cover the API as discussed in https://github.com/fastlane/ci/pull/938
