### ISSUE TITLE
Add project with specific branch

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#456]
Depending on the project type:
- Any project: Define a list of branches to run, or a list of branches to ignore
- PR based projects: Define a default target branch, and a list of branches to ignore
- [ ] Use branch that is selected in the add project flow when we peek the Fastfile in github, or even when we need to checkout out the repo to look for a fastfile.

**Comment by minuscorp** [comment]
As we have conceptually defined a `Project` is: `Branch` + `Lane` + `Triggers` <- (on the selected `branch`) how do we fit this in the current behavior?

**Comment by KrauseFx** [comment]
Yes, this is a great feature, but I feel like something we don't yet need for a successful beta release, moving this to the 1.0 milestone for now 👍
