### ISSUE TITLE
Support for distributed builds

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#457]
- Have a way of having a master node and multiple worker nodes
- The worker nodes ask for tasks from the master node
- This allows teams to scale up `fastlane.ci`

This task includes transferring of all required metadata for a build, meaning the git repo details, branch to run, lane to run, and the environment variables set for the build (https://github.com/fastlane/ci/pull/465), and the environment variables set by the user

**Comment by KrauseFx** [comment]
Blocked for now, please don't grab this task

**Comment by minuscorp** [comment]
BTW, just leaving this here: https://github.com/mperham/sidekiq 
I have kind of strong experience in distributed task queues and so on, so I want you to know that you can rely on me 😊

**Comment by taquitos** [comment]
For distributed builds, we're probably going to be working with a solution that doesn't require installing/maintaining another piece of server infrastructure like separate queues. The goal of distributed builds is to have multiple macs with `fastlane.ci` installed that find each other, and then configure themselves to be headless nodes in a cluster with 1 mac being the server and delegating out tasks.
Goals:
-  Keep setup and maintenance dead-simple
-  No extra software packages needed
-  Automatic configuration
-  One server node to manage ci-config repo prevents races
-  One server node to manage artifacts prevents races
-  One server node to rule them all

**Comment by AndrewMcBurney** [comment]
> - One server node to rule them all

![image](https://user-images.githubusercontent.com/8942499/38755798-1914e89a-3f35-11e8-9eb2-f040287e23d0.png)

**Comment by minuscorp** [comment]
I can't figure out a messaging system that does not rely on third-party libraries (unless we actually make one ofc 🤣 ), I meant as for operating system level. Maybe a TCP socket-based locking system could be a nice feature to make use of.
Just throwing out ideas that comes into my mind 🙃

**Comment by taquitos** [comment]
I'm ok with third-party libs, we just don't want to install a separate, stand-alone piece of server infra, which is what you generally have to do in traditional queues.

Really though, I think we can go very simple. My first thoughts are: [bonjour](https://developer.apple.com/bonjour/) + [grpc](https://grpc.io/docs/tutorials/basic/ruby.html).

**Comment by minuscorp** [comment]
Seems legit too. Maybe easier that what I've proposed 🤣

**Comment by Ashraf-Ali-aa** [comment]
@KrauseFx I was thinking of adding support for the real devices and simulators on the worker node, but I was wondering how does the fastlane.ci child node work, I was planning on porting over a some of the features of Hive CI but on Hive CI worker node runs a daemon process similar to like a server that polls USB connected devices and then reports back to a server called Hive mind that is used to determine if the device is ready to run UI tests.

More info about Hive CI:
http://bbc.github.io/hive-ci/documentation/overview.html

**Comment by KrauseFx** [comment]
Hey @Ashraf-Ali-aa, we're currently actively working on the worker system with https://github.com/fastlane/ci/pull/951, so for now, please don't work on that code as we'll change it 👍 Thanks for offering to help
