### ISSUE TITLE
Handle case where account can't create a private repo

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#463]
Via https://github.com/fastlane/ci/commit/0a12b127840bfaf092f2660501993e6fc31d28ca
This will happen quite often

**Comment by AndrewMcBurney** [comment]
Should we add this to the `Alpha` milestone? I'm wondering because I know from experience it can be frustrating when onboarding doesn't work correctly (and I'm the one to blame because I wrote a lot of it :joy:)

**Comment by KrauseFx** [comment]
Good idea - we want to finish the Alpha version by the end of this week, so we probably don't have enough time. In particular rendering error messages is something we haven't yet fully ready to be used AFAIK 👍

**Comment by KrauseFx** [comment]
I actually don't know the status on this issue, this is something we'll have to look into and potentially invest more time in

**Comment by nakhbari** [comment]
Is this still targeted for Beta?

**Comment by KrauseFx** [comment]
I think we at least have to look into this, as this would be a blocker for onboarding for a majority of our users, many GitHub users may have a paid org, but not a paid personal account

**Comment by dhandapani-d** [comment]
We are trying fastlane ci Alpha and blocked because of this issue. Is there any workaround to try fastlane ci without githup private repo? 

Just curious to know, Why there is such restriction? User should be able to use any repository, / even bitbucket or something else right. Any reason behind this?

**Comment by KrauseFx** [comment]
We make heavy use of the GitHub API, so it is specific to GitHub. In theory the repo might be public, however it does add a potential security risk. 

Would a public GitHub repo work for you also? Or do you need to use BitBucket?

**Comment by dhandapani-d** [comment]
Public GitHub repo would work for me.

Is it like to focus on MVP there is a tight integration with GitHub API? But in long-term fastlane-ci should be independent of any repository / version control system other than right. Is that correct?

**Comment by dhandapani-d** [comment]
Saw your related comments in #604 . Makes sense. Looking forward to for the next release with GitHub public support. Thanks for such great project.

**Comment by witchlock** [comment]
It would be great if bitbucket is supported too.
