### ISSUE TITLE
Investigate and fix dead git configurations

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#483]
After running fastlane.ci for a while, running `git config -l` will print out a ton of things that we should probably clean up

```
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
credential.helper=store --file /Users/felixkrause/.fastlane/.tmp/git-auth-f4ad792fd66dbac4d1b5522c7e1ada9b79fca376aea655d0a1d4f3e375b7057e
```

**Comment by minuscorp** [comment]
We should catch server kill and clean `git-auth-*` paths?

```ruby
Signal.trap('INT') { throw :sigint }

catch :sigint
    cleanup_gitauth_paths
end
```

**Comment by minuscorp** [comment]
It seems that `thin` is already catching all signals by default, so it's not being easy to ensure that on close time we can cleanup those temporary files.

**Comment by taquitos** [comment]
It's also not just file clean up, it's actually git-config stuff. If you notice `credential.helper` lists the same file multiple times.
I think we need to check if that `credential.helper` is already using the file and then not add it again to the config. This should probably be fixed in `git_repo`

**Comment by minuscorp** [comment]
As shown in `git credential` documentation:
- [Reference](https://git-scm.com/docs/git-credential-store/1.7.12.1): 
> Using this helper will store your passwords unencrypted on disk, protected only by filesystem permissions. If this is not an acceptable security tradeoff, try git-credential-cache[1], or find a helper that integrates with secure storage provided by your operating system.

So in: https://git-scm.com/docs/git-credential-cache
> This command caches credentials in memory for use by future Git programs. The stored credentials never touch the disk, and are forgotten after a configurable timeout. The cache is accessible over a Unix domain socket, restricted to the current user by filesystem permissions.

So maybe for security and lack of persistence, this second approach might be more useful, we can target it for `Beta`

**Comment by taquitos** [comment]
`git config --global --edit` to edit by hand for now
