### ISSUE TITLE
Figure out when we can remove temporary code, that's blocked by some task

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#514]
https://github.com/fastlane/ci/blob/master/app/features/global/layout.erb#L12
```html
    <!-- 
    <%= erb :"../../partials/notification_banner" %> 
    -->
```
This is code that doesn't seem to work, so we commented it out, and we don't know yet when we can enable it again.

Blocked by unknown currently

**Comment by taquitos** [comment]
Code works, it just stays on the page. Needs to be styled or something to only show when there is a notification to display.

**Comment by KrauseFx** [comment]
I guess this can be removed with the ongoing front-end work eventually gonna replace this anyway? If so, feel free to close @taquitos 👍

**Comment by taquitos** [comment]
Good point @KrauseFx, we're going to remove all this in the future.

**Comment by KrauseFx** [comment]
Getting things done, the right way ✅
