### ISSUE TITLE
Use Gemfile and Gemfile.lock of the user if it exists

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#555]
When checking out a repo, we should check if there is a Gemfile and Gemfile.lock and then use them. This might require us to run `bundle install` on it. We'll need to investigate on how to best handle it

**Comment by KrauseFx** [comment]
There are some Bundler methods, like `Bundler.setup` and `Bundler.with_clean_env`

**Comment by minuscorp** [comment]
Is this free? I'd like to assign to myself if anyone else wants it!

**Comment by KrauseFx** [comment]
@minuscorp ah, just saw your comment, I took a look into this, and seems like it's trickier than expected. Make sure to also assign yourself to https://github.com/fastlane/ci/issues/598

The issue I have that both `Bundler.setup` and `Bundler.require` don't seem to properly load the defined dependencies of the project's Gemfile, but just use the fastlane.ci Gemfile instead. 

It seems like it might be related to https://github.com/bundler/bundler/issues/1041, but not 100% sure.

**Comment by KrauseFx** [comment]
Yes, feel free to grab this task

**Comment by minuscorp** [comment]
I've been reading the docs a little bit this afternoon and see that is possible to let bundler know which directory use to load and install the gems, but just was a quick read. I'll dig into this as soon as possible!
