### ISSUE TITLE
Creating a project that runs time-based doesn't allow manual trigger

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#568]
I know there was some previous discussion about this - not sure if that's decided yet. But it's pretty unpractical and almost impossible to set up if I can't manually trigger a build. I'll have to wait for a few hours to see if the build is green, and then if I do a fix, I'll have to wait for 24 hours? :trollface:

**Comment by KrauseFx** [comment]
I want to also add the manual trigger by default

**Comment by taquitos** [comment]
We never decided that we shouldn't add a manual trigger by default. 
IMO we always should, unless explicitly removed. In that case, we should message what removing means and the downsides of testing the project.

Also, it might make sense to be able to remove the manual trigger later on.
