### ISSUE TITLE
Build.rb should store all the parameters we used for this particular run

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#570]
We should store the `lane`, and any other required parameters/information to be able to re-run the build and show the `lane` name in the build details

This will also be needed for https://github.com/fastlane/ci/issues/558

**Comment by taquitos** [comment]
It's likely we'll want to store the trigger.
I think the trigger should encapsulate all this stuff

**Comment by KrauseFx** [comment]
Sounds good. The trigger doesn't include the lane thought I think, it's part of the `Project` object 👍

**Comment by KrauseFx** [comment]
This is something we should do for the beta, as it probably won't be backwards compatible

**Comment by KrauseFx** [comment]
Also kind of related to https://github.com/fastlane/ci/issues/481

**Comment by taquitos** [comment]
Yeah, I think we want the lane to still live on the project. So that means:
Build is what you get when you mash together a project + the trigger
