### ISSUE TITLE
Build status should include link to the CI system for easier access of error information

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#573]
This way on GitHub, there is a `Details` button that goes straight to the build output. This will require us to add some kind of system to allow the setting of a CI host URL or similar I think

**Comment by KrauseFx** [comment]
<img width="783" alt="screenshot 2018-04-05 11 50 09" src="https://user-images.githubusercontent.com/869950/38346409-8a2c213e-38c7-11e8-93d8-d9eb62f29280.png">

**Comment by taquitos** [comment]
This is actually more involved because it exposes a problem with our authorization. Still digging in.

**Comment by KrauseFx** [comment]
This is complete for now, from what I see 👍 Nice!
