### ISSUE TITLE
Print out of summary tables of fastlane output

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#575]
Tables like
```
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 2 |
| Number of failures | 1 |
+--------------------+---+


+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | scan                       | 64          |
+------+----------------------------+-------------+
```

We currently don't print at all in the output. This is due to the way we render them using `terminal-table` and using the `puts table` command.

**Comment by KrauseFx** [comment]
Ha, this is actually a funny issue, it will require an update in _fastlane_ to use `UI.message(` for printing out every table, across the whole code base. I'm not sure how to pass the resulting string to a message, but I'm sure it's somehow possible 👍

**Comment by nakhbari** [comment]
@KrauseFx Is this still targeted for Beta?

**Comment by KrauseFx** [comment]
It's probably just a 15 minutes task, so I'd be in favor to keep it in beta for now 👍
