### ISSUE TITLE
Implement basic error handling

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#578]
e.g. if a project has 5 builds and the user accesses `http://localhost:9292/projects_erb/b3e59ea4-9259-48e4-9743-ca7832921442/builds/11`

or if a project can't be found, and similar

**Comment by taquitos** [comment]
@KrauseFx is there anything else you were thinking about with this issue? I'm not sure I understand what else we can do (or should).

**Comment by taquitos** [comment]
Anything to surface the errors and make filing an issue easier. 
Maybe if we can even suggest `please run with DEBUG=1 and then paste the output in a new issue` would be enough

**Comment by minuscorp** [comment]
I think that Sinatra provides a global `on error` handling so maybe it'd be useful to make it work to ease the report by users

**Comment by KrauseFx** [comment]
This might need some more love with the new front-end work, tagging it as such for now 👍
