### ISSUE TITLE
Fastfile finder uses the project's work directory containing all the checkouts

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#582]
I saw this output while using fastlane.ci
```
Ugh, multiple Fastfiles found, we're gonna have to build a selection in the future
```
I digged in further, and found the `fastfiles` array in `ci/app/shared/fastfile_finder.rb` had the following value:
```
[ "/Users/felixkrause/.fastlane/ci/b3e59ea4-9259-48e4-9743-ca7832921442/manual_build_ed24f493-52e3-4151-b2a1-bc52798e2ee9/fastlane/Fastfile",
 "/Users/felixkrause/.fastlane/ci/b3e59ea4-9259-48e4-9743-ca7832921442/manual_build_b5f5e186-b46d-4c48-87d0-e9ae4bc5758a/fastlane/Fastfile",
 "/Users/felixkrause/.fastlane/ci/b3e59ea4-9259-48e4-9743-ca7832921442/manual_build_fa0ea088-355b-4e3b-bc37-1450ae67c5a1/fastlane/Fastfile"]
```
^ many more than that actually

The stack is
```
 "/Users/felixkrause/Developer/ci/app/shared/fastfile_finder.rb:24:in `search_path'",
 "/Users/felixkrause/Developer/ci/app/features/project/project_controller.rb:257:in `block in <class:ProjectController>'",
```

So in `project_controller`, we gotta make sure to pass the right `path: ` value, not the whole working directory

**Comment by KrauseFx** [comment]
I know there have been some changes to this code recently, but I have to admit, I don't know the current state. Does finding the Fastfile work now, after running multiple builds? cc @taquitos @minuscorp

**Comment by KrauseFx** [comment]
Might be related to the original issue of https://github.com/fastlane/ci/issues/605

**Comment by minuscorp** [comment]
As far as I've tested recently, this haven't happened to me anymore, but I'll try to test it this week to double-check
