### ISSUE TITLE
Automatically kill inactive builds

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#595]
If a build gets stuck or in an endless loop, we should probably kill that after some time. The # of seconds should be configurable as part of one of the JSON files, probably project specific

**Comment by taquitos** [comment]
Yeah, I think you're right @adellibovi. We should allow for aborting a build manually. Also, we might want to allow a property in the project that allows people to set a timeout. I agree most people might not know the best setting for that, so maybe we just allow it to be in the json, but don't have UI for it. That way more advanced users can still it. What do you think?
