### ISSUE TITLE
Feature: Support GitLab

### ISSUE THREAD

**Issue by viezel** [fastlane/ci#604]
We are trying out the alpha release and such a great tool in the making.
We mainly use self hosted GitLab as it offers many extra features and full control over repos, similar to your vision of self hosted CI. 

Is it on the roadmap to include support for GitLab?

**Comment by taquitos** [comment]
We built the system with a really extensible architecture to allow for it to include many different code hosting services like GitHub, BitBucket, GitLab, etc. We focused on GitHub as the first provider, so we can get all those pieces right in our 1.0 release. After that, anybody can contribute their favorite provider 🎉

**Comment by viezel** [comment]
@taquitos make sense. Thanks for the reply. 👍 

Off topic: the only negative feedback i have: why have a private repo with projects and users. It seems weird compared to having it in filesystem or db. I think app config and settings should be with the app, not on a remote git repo.

**Comment by tkrajacic** [comment]
I agree with @viezel. The requirement to have a paid GitHub account makes the project a non-starter for many I guess and as far as I can see it can be avoided by not putting the credentials in a remote repository. (Which is a shame, as the project is incredible! A big thank you to all the contributors!)

If one is not completely ignorant of what is happening nowadays it is generally a good idea not to put your credentials in the hand of any (US based) cloud service.

**Comment by KrauseFx** [comment]
Interesting, thanks for sharing all of this. I guess we could easily offer an option to keep the git repo locally only for the `ci-config` at least 👍 However for now we'll still have to require a GitHub account, as we use it for many parts of the `fastlane.ci` system, in particular the PRs. Again, in the future we do want to support more code hosting providers, it's just that we want to limit the scope in the beginning.

The reason why we want to put the config into a remote git repo, is that if your CI machine breaks, you don't lose any of the configuration or data, but you can just get a new Mac, and booom, you're back online 🚀

**Comment by viezel** [comment]
@KrauseFx Thats what remote database servers are for. Not repos :) 
At least, in GitLab, it should be possible to do all MRs, commits, status update, pipeline changes using the API only. No user is needed.

**Comment by viezel** [comment]
I know its early - and I really dont wanna hate here. Just would like you guys to succeed in this excellent vision you got 👍 Choosing simple dependencies decoupled from the provider would make it easier to maintain and also add support for multiple providers.
