### ISSUE TITLE
Onboarding lane selection should be much faster

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#610]
When adding a new project, selecting the branch is fast, but selecting the lane is really slow. We can do much better.

- Do we do a shallow clone?
- Additionally we should clone just a list of files, meaning let's check if `fastlane/Fastfile` or `.fastlane/Fastfile` is there, if not fallback to clone the whole repo

**Comment by taquitos** [comment]
We can attempt to check out just the fastfile into a temp directory instead of cloning the whole repo. GitHub has great api for this, and we make use of it in `configuration_repository_service.rb`, specifically in `def remote_file_a_json_array?(file_path)`

**Comment by minuscorp** [comment]
This is something I can take a look into if you want

**Comment by taquitos** [comment]
@minuscorp I already assigned this to myself, and I'm about to push my updates 🎉
