### ISSUE TITLE
Poll: Make use of GraphQL

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#614]
After the `ViewModel` pattern not being the best approach for now, I've been thinking (and in slack it seems like it has a pretty welcoming) to propose GraphQL as the tool to communicate data sources with the frontend.

Leave your 👍👎 comments and thoughts!

**Comment by minuscorp** [comment]
Yep of course! 🙌

**Comment by minuscorp** [comment]
As a sneak-peak (fans, try to chill 😉 )
https://repl.it/@minuscorp/PurpleUnusedCrypto

**Comment by adellibovi** [comment]
Where the ViewModel pattern has been discussed? Couldn’t find any references

**Comment by minuscorp** [comment]
#566

**Comment by adellibovi** [comment]
thanks @minuscorp, to me it looks that the "issue" there was more about the meta programming instead of ViewModels by themselves, right?

**Comment by minuscorp** [comment]
Of course that PR was a proposal of the viewmodel architecture from my point of view, not that it is a source of truth. We're trying to get to the best solution that fits our needs. Other proposals are welcome of course!
