### ISSUE TITLE
Display number of unread notifications on the notifications tab

### ISSUE THREAD

**Issue by AndrewMcBurney** [fastlane/ci#626]
I was thinking something like a red circle with a number denoting the number of unread notifications:

<img width="842" alt="screen shot 2018-04-08 at 12 55 47 pm" src="https://user-images.githubusercontent.com/8942499/38470108-4e62e252-3b2c-11e8-9159-28bf05f458ca.png">

**Comment by minuscorp** [comment]
https://getmdl.io/components/index.html#badges-section 🧡

**Comment by taquitos** [comment]
This is a great idea, let's wait a little bit before moving forward with it. Once we have our Angular frontend in place, that would be 💯
