### ISSUE TITLE
Fasfile finder should recurse repo looking for fastfile

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#638]
If the fastfile isn't located at `repo/fastlane/fastfile` and we need to checkout the repo, let's make sure we recurse the entire project to find it.
- potentially might have multiple.
- let's use breadth-first search to find the parent-most file, and assume that the first one we find is the right one (for now)
- Addresses one issue found in https://github.com/fastlane/ci/issues/605

**Comment by adellibovi** [comment]
Naive question, couldn't we just use `Dir["**/Fastfile"]`?

**Comment by taquitos** [comment]
Hah, yup 🤦‍♂️ 

Also, as a second task, I was thinking still breadth-first, but using GitHub's api to search the repository for it and download the single file (modifying `fastfile_from_github` to support that)

**Comment by adellibovi** [comment]
Will prepare a PR for the first task and have a look of what else GitHub API offers ☺️ Keep you updated!

**Comment by taquitos** [comment]
I dipped my toe in it, and it seemed like you can request the root, which returns an array of ref objects, and you can then check their `.type` which will be either `:file` or `:directory`
We have `def remote_file_contents_map(repo_full_name: nil, sha_or_branch:, path:)` in `fastfile_peeker.rb` that could totally be used to help you make the request

**Comment by taquitos** [comment]
@adellibovi when you get a chance, can you assign yourself to this issue if you're still working on it? That way nobody else starts to work on it too 🚀

**Comment by adellibovi** [comment]
@taquitos not sure I have permission to assign to myself 🤔

**Comment by taquitos** [comment]
ugh, github and their silly permissions
