### ISSUE TITLE
[Idea] Easy way to sync dSYM files

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#641]
Context about why this is useful: https://krausefx.com/blog/download-dsym-symbolication-files-from-itunes-connect-for-bitcode-ios-apps

We can offer the user to set this up for them. What's really nice is that we could submit a PR to their repo adding either the finished Fastfile, or appending a lane to their existing Fastfile (more details on the PR feature idea https://github.com/fastlane/ci/issues/642)

**Comment by taquitos** [comment]
Yes! And we could set up a nightly job, or even a job that runs every X minutes until we have the updated dsyms!

**Comment by KrauseFx** [comment]
So beautiful 👍
