### ISSUE TITLE
Build a system that allows global, project and branch specific settings

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#643]
It looks like for some things we'll have 3 levels of where the value comes from. Examples are: Xcode version, and environment variables. The levels are

- **Global setting**: Default global Xcode installation, which is used unless overwritten by any of the other settings
- **Project-level setting**: A project defines a particular Xcode version, as it wasn't migrated to the new version of Swift yet
- **Branch-specific setting**: The `swift-5-migration` branch need to use the new Xcode beta to be able to compile & run tests

All of the above should be applied to all settings where it makes sense. Out of the top of my head, this might just be Xcode version, and the environment variables 👍 

Existing issues:
- Edit project-specific environment variables: https://github.com/fastlane/ci/issues/441
- Edit the global fastlane.ci environment variables https://github.com/fastlane/ci/issues/439

**Comment by christoff-1992** [comment]
Will this include upload parameters such as,

DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"

It would be useful to globally configure these as this is environment specific not project.

**Comment by taquitos** [comment]
@christoff-1992 since we use `fastlane` internally, we should get this global behavior for free 🎉 
Our plan is to allow you to also specify any arbitrary environment variable at the project-level, as well as branch-level too.

Did you try using this environment variable and have issues in fastlane.ci?

**Comment by christoff-1992** [comment]
@taquitos - No issues with the environment variable that sounds perfect to me :)

**Comment by KrauseFx** [comment]
So my current thoughts are:

### Global ENV variables

Store them in `environment.json` in the root of the `ci-config` repo

### Project specific ENV variables
We have a few potential solutions:
- `[ci-config-repo]/projects/[project_id]/environment.json`: this will allow us to offer something similar for other types of configuration for the `project-level`. For branch specific options we could just use `[ci-config-repo]/projects/[project_id]/branches/master/environment.json` (store env variables in separate file per branch) or `[ci-config-repo]/projects/[project_id]/branches/environment.json` (store info of all branches in a single file)
- `environment.json` could have 2 keys in the root hash: `global`, `project`, kind of like:
```json
{
  "global": {
    "FASTLANE_DISABLE_YOLO": false
  },
  "project": {
      "[project_id]": {
          "env": {
              "FASTLANE_DISABLE_YOLO": true,
          },
          "branches": {
              "develop": 
                 "FASTLANE_DISABLE_YOLO": 123,
              }
          }
      }
}
- Store the project and branch specific settings as part of `projects.json`. This feels like it will potentially bloat up the `projects.json` file by quite some.

----

Personally I think we should have an `environment.json` in the roof of the `ci-config` and then store project/branch specific information in `ci-config/projects/[project-id]/environment.json`

While building this, I'll keep in mind that `environment.json` probably won't be the last kind of configuration where we want projects to be able to override global settings :+1:

**Comment by minuscorp** [comment]
This make me think, at which point we should stop to add information in `projects.json` level and when we should make customized configuration files. I think that, with this topic being raised, we should try to tie the limits of the information stored by which file (looking a bit in the future for plugins: their configuration, artifact providers: should the project store its whole information or it should be a separate config file, etc.). I agree with you that we can end up bloating up the `projects.json` if we don't establish the scope and purpose of the file itself, and therefore, the model and their relationships.

**Comment by KrauseFx** [comment]
Yeah very much agreed. That's why I'm a fan of splitting this out, making it a lot easier to edit those files manually if necessary

**Comment by taquitos** [comment]
💯 to this all. Make a ton of sense, and we can even use the JSONDatasource for it all. Such a great addition to our project!

**Comment by KrauseFx** [comment]
Just to clarify, after talking with @nakhbari in person, this is only related to the user-managed environment variables, and is not related to the variables stored in `.keys` 👍

**Comment by KrauseFx** [comment]
I feel like branch specific settings are very advanced, and not something we need for a 1.0. So I set up this issue to be closed once the PR is merged 👍
