### ISSUE TITLE
Add button on dashboard for people who want to talk to us about fastlane.ci

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#645]
As we continue to build out fastlane.ci, we'll want to make sure we gather feedback from people who are using the Alpha and Beta. Let's add a button somewhere and link it a form people can fill out if they want to help contribute to making fastlane.ci the ci of their dreams 🌈 

Moving forward, we'll probably want to link to a short questionnaire, and then, if people are interested, we'll actually invite them for a face-to-face (either in-person in the SF Bay Area, potentially NYC, or over VC 📺)

So for right now, maybe we can build a button that describes this idea and sends an email to `fastlane@google.com`.

**Comment by nakhbari** [comment]
Maybe later on we can add a CSAT survey since they come from an external link. It would be like 1 line of code.

**Comment by minuscorp** [comment]
What about the discussion forum we talked about _fastlane_ but just for _fastlane.ci_? 😄

**Comment by KrauseFx** [comment]
@minuscorp what do you mean?

Alright, we have the link with a simple Google Survey for now, let's close this for now 👍

**Comment by minuscorp** [comment]
About a discussion forum with the community besides the issues related with the CI itself
