### ISSUE TITLE
Add TS Lint to Fastfile

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#657]
We have a TS linter set up, let's add it to the Fastfile so every frontend PR can be linted.

**Comment by KrauseFx** [comment]
Ah nice, can you link me to the TS linter we're using? Is it prettier?

**Comment by nakhbari** [comment]
This is the standard linter for TS.

https://palantir.github.io/tslint/

config:
https://github.com/fastlane/ci/blob/master/tslint.json

**Comment by taquitos** [comment]
> frontend CL
😆 frontend *PR*

**Comment by KrauseFx** [comment]
Thanks 👍

**Comment by nakhbari** [comment]
Fixed by add tslint to the Fastfile #658
