### ISSUE TITLE
Can't start fastlane ci server

### ISSUE THREAD

**Issue by imodeveloper** [fastlane/ci#664]
fastlane ci 1.0.0.alpha.1

After I follow the onboarding instructions and successfully finished all instructions, I was unable to add new project (Internal server error), I tried to stop and start server again and I got this: 

<img width="1033" alt="screen_shot_2018-04-13_at_11_04_06_am-3" src="https://user-images.githubusercontent.com/2129457/38726812-8b39a912-3f0b-11e8-888a-6aa5b7490bc4.png">

**Comment by KrauseFx** [comment]
Hey @imodeveloper, thanks for reporting this. Can you confirm this is still happening with the most recent code from `master`?

**Comment by imodeveloper** [comment]
Hi @KrauseFx, sorry for late answer, I tried today, so with commit #2b8f587 server started with success 🎉and dashboard starts to.

<img width="680" alt="screen shot 2018-04-19 at 9 36 49 pm" src="https://user-images.githubusercontent.com/2129457/39014145-d3dbf3e2-4419-11e8-8604-7265f067d110.png">

<img width="1074" alt="screen shot 2018-04-19 at 9 41 30 pm" src="https://user-images.githubusercontent.com/2129457/39014366-7519a0c4-441a-11e8-8837-f39077b7496c.png">

**Comment by taquitos** [comment]
Yesss thank you for getting back and confirming! I'm going to close this issue. Feel free to keep opening issues if you encounter anything!
