### ISSUE TITLE
Relative Pipe for the latest build Date

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#666]
Parent Issue: https://github.com/fastlane/ci/issues/644

Create date pipe so our build times can be represented relatively. ex. "30 seconds ago"

This would be our first pipe. Should go under `common/pipes`

Could use something similar to what's listed here: https://gist.github.com/JonCatmull/e00afb1c96298a4e386ea1b5d091702a

**Comment by minuscorp** [comment]
Am I allows to use third-party libraries for this? Like [Moment.js](https://momentjs.com/)

**Comment by KrauseFx** [comment]
Related to https://github.com/fastlane/ci/issues/488

**Comment by KrauseFx** [comment]
@minuscorp I think third party libraries are ok, as long as they're MIT licensed

**Comment by nakhbari** [comment]
I think moment js is fine for this. I think if we were to use moments instead, we wouldn't need a Pipe since we could just do `. fromNow` method.
