### ISSUE TITLE
Chrome - Textfield Placeholder Bug

### ISSUE THREAD

**Issue by jwelton** [fastlane/ci#671]
There appears to be a bug with the placeholder field. I'm using Chrome Version 64.0.3282.167 (Official Build) (64-bit)

![screen shot 2018-04-14 at 7 53 53 pm](https://user-images.githubusercontent.com/5704178/38771590-a2fce678-401d-11e8-99df-e5ff1b292ae2.png)

**Comment by KrauseFx** [comment]
Thanks for reporting this, the front-end will be completely re-written using Angular, so this whole screen will be replaced soon 👍 I'll close this for now.

Keep those reports coming, really appreciated :)

**Comment by nakhbari** [comment]
Closed for the reasons @KrauseFx mentioned.

**Comment by KrauseFx** [comment]
Oh whops, I meant to close it, thanks @nakhbari 👍
