### ISSUE TITLE
Be able to select what branch we want to use for a project

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#68]

**Comment by KrauseFx** [comment]
Context: We already have a project editor, with a lane selection. We should think about how we want to do the branch selection. Each project is specific to a repo and a lane (you can only run one lane per project, to run more lanes, you create multiple projects, e.g. nightly, release, etc.)

Branch is not just selecting a branch, we should think about how we do it in a bigger way.
Some use-cases (we don't have to cover all of them right away)

- Run builds only on `master`
- Run builds only for PRs and `master`
- Run builds for every commit (even no PRs)
- Run builds for `master`, `develop`

We don't have to build the whole UI and everything to support all of this, however we should think about supporting those long-term, so ideally we come up with a way to store this setup in our persistence layer already. 

I'd also be ok with just providing a list of branches and storing that, and ignoring the PR or no PR thing for now, as this could be a separate toggle.

**Comment by minuscorp** [comment]
We can figure out a vocabulary model to define the rules that apply to a project. Early idea: `"@master&@PR&!develop"` use `&` to concatenate rules, `operator+branch` to define which branch or other reserved words to build out not. I think that'd be easy to formalize and implement. What do you guys think? 😁

**Comment by KrauseFx** [comment]
For now, let's make it super basic, and just allow a single branch? Are there any standards other CI systems have already?

**Comment by minuscorp** [comment]
So in Jenkins is the most rough way, where you use `refs/<branch>` or wildcards like `/refs/*`. Other CI I know are more like three main options: 1) build all new branches by default (you can later disable manually new branches created). 2) automatically build all PRs. 3) automatically build all tags.

**Comment by taquitos** [comment]
I've been thinking about this and I actually don't know if we need to do anything here. If we do all configuration via fastfile, and in the fastfile we specify what branch we're using, do we really want to define what branch we're using in fastlane.ci too? That means we have to override the fastfile in the project, which doesn't seem like a good idea. Instead, maybe in the future you can modify your fastfile, or have alternate fastfiles.

**Comment by KrauseFx** [comment]
> If we do all configuration via fastfile, and in the fastfile we specify what branch we're using, do we really want to define what branch we're using in fastlane.ci too?

Yes, I think we still need to. One example is: I want to run `fastlane release_to_app_store` only on the `release` branch. `fastlane.ci` will be used for testing on probably all (`*`) branches, but quite often I think people will use it for e.g. weekly beta deployments or App Store deployments also.

**Comment by taquitos** [comment]
Ah, ok, so maybe the implementation detail could be that we pass the branch information as a parameter to the lane? That way we keep all branch management for lanes in the `Fastfile`

**Comment by KrauseFx** [comment]
I think that will cause issues long term. One thing that comes to mind is that the Fastfile might/will be different for each branch. From what I see, it has to be on a different layer (being the CI). Luckily there is not a lot of things where that's the case, but the Git URL, branch, lane to run are some of them

**Comment by taquitos** [comment]
Good point ☝️

**Comment by taquitos** [comment]
At this point, we have the following:
Project (repo + lane)
 -  Triggers
 -  Each trigger can have a different branch

So when you select a branch, you'll want to update the appropriate trigger (or create a new one) with the branch selected 🎉

**Comment by nakhbari** [comment]
Correct me if i'm wrong here.
In summary, in order for users to be able to perform different tasks on different branches we'll allow them in the projects json to specify which branch and which lane to use. And should they not be provided we'll use master, and the first lane respectively?

**Comment by taquitos** [comment]
A project is actually a repo + lane(a lane can be thought of as a task)
A trigger can act on a specific branch (master being default)

Lanes can range from "build and test" to "build, test, sign, distribute". So while a lane represents a task, a task can be a single action, or it can be multiple actions.

Since lanes can be super complicated, we wanted to have a single project represent just a single lane.

**Comment by KrauseFx** [comment]
Is this still a WIP? Note that I just created a new card that's kind of related: https://github.com/fastlane/ci/issues/236

**Comment by nakhbari** [comment]
This should be done now
🚀
