### ISSUE TITLE
Add coverage reports from Angular application

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#681]
We now have nice coverage reports for all Ruby codebase, but as the Angular application is growing, having a knowledge of the coverage is getting more and more important everyday.
Talked with @nakhbari and it seems that [Coveralls](https://coveralls.io/) has [Jasmine](https://jasmine.github.io/) [support](https://github.com/nickmerwin/node-coveralls), so this is an open task for whoever wants to add JS coverage support to the project 😄 🚀

**Comment by KrauseFx** [comment]
Nice, yep, I don't know yet how it's gonna work with coveralls, and having things in one repo, etc. We'll need to figure that out

**Comment by minuscorp** [comment]
I have opened #900 to track this issue
