### ISSUE TITLE
Be able to commit changes to a branch

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#69]
- [x] Commit as user
- [x] Commit as ci
- [ ] amend commits

**Comment by AndrewMcBurney** [comment]
Hi @taquitos,

I'm interested in contributing to the project. I saw this issue, and figured it would be a good first problem to tackle.

In terms of implementation details, I was thinking of having three worker classes - one for each of the bullet points.

I was planning on using the `octokit` gem (which I saw is included in the [`Gemfile`](https://github.com/fastlane/ci/blob/master/Gemfile#L14)) to communicate with the GitHub API.

Could I please get a little more context about how you would like this feature to integrate with the existing codebase?

Thank you! :slightly_smiling_face:

**Comment by KrauseFx** [comment]
Hey @AndrewMcBurney, thanks for offering to help out. Actually we already built the committing code as CI and as user, so there is no work left on this task 👍 Sorry for still having this card around, not being up to date

**Comment by KrauseFx** [comment]
Check your inbox 👍

**Comment by KrauseFx** [comment]
I'm not sure what `amend commits` means in this context, so I'm gonna close this for now 👍
