### ISSUE TITLE
Build directory is being created in wrong places

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#699]
After a manual trigger being done on one of my example repos I end up with the following `~/.fastlane/ci` directory tree:
```
.
├── 5bf2a0f7-cfdb-43f0-aa0d-065e76e53bc8
│   ├── Gemfile
│   ├── Gemfile.lock
│   ├── README.md
│   ├── builds
│   ├── fastlane
│   ├── fastlane-ci-demoapp
│   ├── fastlane-ci-demoapp.xcodeproj
│   └── manual_build_8fa0ecfb-cc15-4693-9839-b6c1632ae095
├── artifacts
│   └── 5bf2a0f7-cfdb-43f0-aa0d-065e76e53bc8
├── fastlane-ci-config
│   ├── projects
│   ├── projects.json
│   └── users.json
└── notifications
    └── notifications.json
```
Which does not seem correct to me (see that `builds` folder, that is not part of the original repo, but generated by the CI inside the structure of the repo, which can lead to issues).

**Comment by taquitos** [comment]
Yup, it looks like we're checking out the project there for some reason
it should be in the `project_id/builds` folder and checked out under the `git sha` for the build.

**Comment by KrauseFx** [comment]
Added some labels + milestone

**Comment by minuscorp** [comment]
`builds` folder should be at root path of the repo? isn't that weird? having the repo checked out and adding a new directory to it? 🤔

**Comment by taquitos** [comment]
The repo shouldn't be checked out there. The repo should be checked out for each commit under the builds folder
The repo should be checked out like this: `project_id/builds/repo_at_commit_sha_we_are_build`

**Comment by minuscorp** [comment]
I have to trace why and when it's the repo being checked out on that directory then, it seems that's being done when triggering a manual commit, even when the manual commit creates its own directory 🙄

**Comment by taquitos** [comment]
Yeah... that might be the case

**Comment by minuscorp** [comment]
Agh, have to get time to tackle this 🤦‍♂️

**Comment by KrauseFx** [comment]
@minuscorp is that still something you work on 👍 Sounds like something that needs to be fixed 💯

**Comment by minuscorp** [comment]
This is what I'm getting now:
```
.
├── 5bf2a0f7-cfdb-43f0-aa0d-065e76e53bc8
│   ├── builds
│   │   └── e493137e7eaa39105a40504351d74ce4e67e660e
│   └── manual_build_ee78c7fa-73f0-484c-ad3e-28d584bb2c08
│       ├── Gemfile
│       ├── Gemfile.lock
│       ├── README.md
│       ├── fastlane
│       ├── fastlane-ci-demoapp
│       └── fastlane-ci-demoapp.xcodeproj
├── artifacts
│   └── 5bf2a0f7-cfdb-43f0-aa0d-065e76e53bc8
│       ├── 62
│       └── 63
```
This seems to be correct (although I didn't made a single change) is this correct? cc @taquitos @KrauseFx

**Comment by taquitos** [comment]
Two things:
1. `manual_build_ee78c7fa-73f0-484c-ad3e-28d584bb2c08` should go under `builds/`
2. `manual_build_ee78c7fa-73f0-484c-ad3e-28d584bb2c08` should probably have a build number appended to it as well, since you could execute multiple manual builds for the same SHA, so maybe:

```
.
├── 5bf2a0f7-cfdb-43f0-aa0d-065e76e53bc8
│   ├── builds
│   │   └── e493137e7eaa39105a40504351d74ce4e67e660e
│   │   └── manual_ee78c7fa-73f0-484c-ad3e-28d584bb2c08_build_01
│   │   └── manual_ee78c7fa-73f0-484c-ad3e-28d584bb2c08_build_02
│   │       ├── Gemfile
│   │       ├── Gemfile.lock
│   │       ├── README.md
│   │       ├── fastlane
│   │       └── fastlane-ci-demoapp
│   │           └── fastlane-ci-demoapp.xcodeproj

├── artifacts
│   └── e493137e7eaa39105a40504351d74ce4e67e660e660e
│       ├── 62
│       └── 63

```

**Comment by minuscorp** [comment]
Will work on it tomorrow!

**Comment by minuscorp** [comment]
So `manual_build_ee78c7fa-73f0-484c-ad3e-28d584bb2c08`, that last number is a `SecureRandom.uuid`
```ruby
checkout_folder = File.join(File.expand_path(project.local_repo_path), "manual_build_#{SecureRandom.uuid}")
```
So there won't be collisions between two manual triggers over the same `sha` that creates a directory with the same name. So I think there's no action to be made here?

**Comment by taquitos** [comment]
Ohh whoops, maybe we should change that to be the SHA of the commit that is being built? That way it's obvious that it's a manual build for a given sha. Then we can append the build number to the end, incase there are multiple builds.

**Comment by taquitos** [comment]
Since we have that data on the page, maybe we should pass it on submission?

**Comment by minuscorp** [comment]
yeah, we only have the `sha` context if we are triggering from a known build, but if we just push the trigger job now button, we don't have that information until we have cloned the repo itself 🤷‍♂️, renaming the folder doesn't seem to me like a good option TBH

**Comment by minuscorp** [comment]
I'll change it so we create the folder with the `sha` and additional number `_01, _02, ...` when `sha` is passed through parameters, else we just fallback to `SecureRandom.uuid` as for now 😄
