### ISSUE TITLE
Poll for changes in git repo

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#70]
- [x] Have some kind of lock system for git repos to avoid multiple workers using it at the same time
- [x] Handle git conflicts
- [x] Also make sure to update all sub modules, and reset any potentially uncommitted changes

**Comment by minuscorp** [comment]
Are you considering (given the multithreaded or even multiprocessed nature of the CI) the usage of some kind of distributed locking, like through Redis or something like that. It shouldn't be hard to achieve and it performs extraordinarily well.

**Comment by taquitos** [comment]
We're thinking about a setup that is more like a traditional compute cluster where you have 1 node that serves as the leader and doles out work to the worker nodes using RPC.

In that case, the lead node will do all the bookkeeping, and locking.

We wanted to avoid more dependencies because we want this system to be super easy to setup and install, so to us, that means being as self-contained as possible.

In our ideal world, you just install 1 app, and everything works.

**Comment by minuscorp** [comment]
So maybe your idea is to centralize the locking system on a master node, are you thinking about a simple filelock approach or something more in-memory oriented?

**Comment by taquitos** [comment]
Yup, exactly. In this particular case, I'm actually about to add a serial [TaskQueue](https://github.com/fastlane/TaskQueue#example) to each repo for in-memory locking.
Right now we're focusing on single ci instances with an eye towards V2 including clustering. I also wanted to update TaskQueue to be optionally backed by a file so that if there is a crash, we at least get a log of what tasks were in the queue.

**Comment by minuscorp** [comment]
So I see that you use mutex to synchronize the tasks in a queue, so the synchronization problem might be resolved for now? Or do you think there is something to be done. About the task save so if something fails a new worker can create the pending tasks again are you thinking on defining some kind of serialization (JASON, XML, YML?) that is able to represent the whole state of a worker at a given moment?

**Comment by nakhbari** [comment]
@taquitos Is part of this task now done with the implementation of TaskQueue?

**Comment by taquitos** [comment]
@nakhbari only part :)
