### ISSUE TITLE
`npm install` adds 36,812 files to `node_modules` subfolder (409.1 MB)

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#702]
Ok, what?

**Comment by taquitos** [comment]
What's the implication of that?

**Comment by nakhbari** [comment]
Was hoping to see if there is anything we can remove as a dependency but upon further review. It's too long and complicated to figure that out. Might need a disk space virtualizer 🙃

**Comment by taquitos** [comment]
I'm just shocked that we need to add 409 MB of dependencies, there must be a mistake somewhere, like, we're talking just javascript, right?

**Comment by snatchev** [comment]
This seems par-for-the-course in the npm world. Babel should reduce it to a few megs for production 
¯\\_(ツ)_/¯

I recognize that a few megs of js is still a lot of text.

**Comment by taquitos** [comment]
I guess the question I have is: having this many dependencies for an Angular project is normal?

**Comment by nakhbari** [comment]
Looks like we're on `5.2.0` angular and `5.2.4` angular material.

I just created a new project with angular cli (without material) and it's also very large 288,155,426 bytes (378.9 MB on disk) for 34,330 items

**Comment by nakhbari** [comment]
This doc might be helpful (haven't looked into it in full) https://hackernoon.com/whats-really-wrong-with-node-modules-and-why-this-is-your-fault-8ac9fa893823
