### ISSUE TITLE
Link the commit shas to their code hosting page

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#708]
Parent issue #682

**Comment by minuscorp** [comment]
I actually need the build section to be built before adding the sha's link

**Comment by nakhbari** [comment]
@minuscorp Can we not add this here? 
![image](https://user-images.githubusercontent.com/2754461/39204748-80750404-47ad-11e8-8f65-6fc3b66a7dfd.png)

**Comment by minuscorp** [comment]
oh wow, I'm an idiot
