### ISSUE TITLE
Push changes to git repo when projects are updated

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#71]
- [x] Push using correct credentials for project configuration (user's)
- [ ] Push changes to project that are made as part of a lane (ci user)
- [ ] handle push failures gracefully (conflicts)

**Comment by KrauseFx** [comment]
We currently don't push at all

**Comment by taquitos** [comment]
#486 now enables pushing after commit by default.

**Comment by KrauseFx** [comment]
Should this and #487 be closed?

**Comment by taquitos** [comment]
Nope, #486 is now closed, but this is to track any changes we made to project fastfiles

**Comment by KrauseFx** [comment]
This should be addressed with https://github.com/fastlane/ci/pull/459
