### ISSUE TITLE
isolate fastlane into separate process

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#733]
- [x] FastlaneRunner to be responsible for launching a new `fastlane` process
- [x] Once fastlane process is up and running, `FastlaneRunner` to connect and start passing commands
- [x] Output from `fastlane` to be piped back to `FastlaneRunner` in real-time so we can display output
- [ ] End result should be two components, one contains sinatra and serves the end points, and the other is all the macOS-required logic, such as the `fastlane` tooling.

The idea here is that the `sinatra` server doesn't require macOS, so we should keep it that way and allow people to run it on a linux machine. When we do this, that means people can host the frontend + web server on a really cheap but fast linux machine, or in a virtual machine on any hardware. At that point, we can have macs be 100% dedicated to being `build executor`s. These `build executors` will be a separate ruby process that the web-server can talk to using `grpc` or something like that, so people can scale their build environment horizontally by buying a new mac.

Check out `fastlane.swift`: https://github.com/fastlane/fastlane/tree/master/fastlane/swift
We do very similar things here, and we should leverage the existing code.
Also, take a look at: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/commands_generator.rb#L139
This is where we start a `socket_server` and listen for connections.

Some rough documentation on fastlane.swift, might be slightly outdated:
```
How does FastlaneRunner call fastlane?
FastlaneRunner connects to a socket server and sends a command, then waits for a response.
Request payload:
{
	"commandID": "",
	"methodName": "installXcodePlugin",
	"args": [{
		"name": "url",
		"value": "http://pluginRepo.com/my_plugin",
"value_type": ""  


	}, {
		"name": "github",
		"value": ""
	}]
}

commandID is meant to help us track invocations locally, but isn’t used currently.
methodName is the action/tool name. 
args is a list of name/value pairs where the name is the parameter name, and the value is the actual value of the argument you wish to pass.
	name parameter name
	value value of the argument we are passing to the method
value_type is used in cases where the parameter is actually meant to be a closure. *This should be extended to support value type encodings like Array, and Hash*

A response payload sent from fastlane back to FastlaneRunner:
{
	"payload": {
		"status": "ready_for_next",
		"return_object": "",
		"closure_argument_value": ""
	}
}
	
status can be 
**ready_for_next**
Will include whatever return object the action returns, or empty
**failure**
Returns failure_information which is the stack trace of the exception thrown from attempting to run the command
```

**Comment by minuscorp** [comment]
I'd love to take a look into this, if no one else wants it!

**Comment by minuscorp** [comment]
Opening the discussion:

`fastlane.swift` has its own `LaneManager` see [[1]](https://github.com/fastlane/fastlane/blob/e8abaad12b50124522e82179f89874eb271333ab/fastlane/lib/fastlane/swift_lane_manager.rb) to run commands from the `Fastfile.swift`. 
1. Consider making a dedicated `ci_lane_manager` that, using the same resources as the Swift runner, can create a runner, using [[2]](https://github.com/fastlane/fastlane/blob/e8abaad12b50124522e82179f89874eb271333ab/fastlane/lib/fastlane/swift_lane_manager.rb#L219), and cruise to a lane making a new `Thread` like [[3]](https://github.com/fastlane/fastlane/blob/e8abaad12b50124522e82179f89874eb271333ab/fastlane/lib/fastlane/swift_lane_manager.rb#L85) after making the proper preparation of the environment (`Bundler`, `ENV`, etc.) and lastly calling like [[4]](https://github.com/fastlane/fastlane/blob/e8abaad12b50124522e82179f89874eb271333ab/fastlane/lib/fastlane/swift_lane_manager.rb#L100) the actual isolated `fastlane` runner.

**Comment by KrauseFx** [comment]
Marking this as blocked for now, as this is something a full-time employee should build, as it's not a one-off task, it will probably require follow-up work 👍
