### ISSUE TITLE
Project Details View

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#74]

**Comment by KrauseFx** [comment]
When opening up a project, we want to show certain information, it's not 100% decided on everything, but a rough outline would be:

- [ ] Project Display Name
- [ ] Git repo URL
- [ ] Last commit & build
- [ ] Active branches and their status

**Comment by KrauseFx** [comment]
This task might have to wait a few more weeks until we have all the data necessary to fully render this page. However we could already build this page with dummy data until then I guess 👍

**Comment by KrauseFx** [comment]
No user story yet, created an issue here to create it https://github.com/fastlane/ci/issues/423

**Comment by KrauseFx** [comment]
Write and implement use-case https://github.com/fastlane/ci/issues/423

**Comment by KrauseFx** [comment]
Initial implementation done :+1:
