### ISSUE TITLE
Checking for existing resources multiple times

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#744]
e.g. for the user, we check in the service, as well as into the data source

- https://github.com/fastlane/ci/blob/master/app/services/user_service.rb#L43-L46
- https://github.com/fastlane/ci/blob/master/app/services/data_sources/json_user_data_source.rb#L170-L178

It seems like we probably don't want to check from inside the `json_user_data_source.rb`, as we might have multiple implementations of the data source in the future, right?

Having the duplicate detection is an issue, as we have inconsistent ways of handling exceptions, and dead code that can never be reached (even though it might be reached in tests, if a class is tested directly)

Thoughts? 🚔

**Comment by taquitos** [comment]
Agreed 👍

**Comment by KrauseFx** [comment]
Alright, solving this for environment variables for now 👍

**Comment by KrauseFx** [comment]
This is basically solved if we implement https://github.com/fastlane/ci/issues/761

**Comment by KrauseFx** [comment]
Moving this to 1.0 so we can check back later if this is solved already 👍 Seems more like a small detail, than a crucial thing to change
