### ISSUE TITLE
[Idea] Parse and show iOS test results natively

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#748]
As this is a mobile CI, and in the beginning we focus mostly on iOS, we have a great opportunity to build something really nice:

With [fastlane](https://fastlane.tools) and with that [fastlane scan](https://fastlane.tools/scan) which uses [xcpretty](https://github.com/supermarin/xcpretty) to parse the build output and test results.

Currently we seem to parse the JUnit file that's generated by xcpretty ([code](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/test_result_parser.rb)), however we could access the xcpretty classes directly also.

By parsing the test results, we can show a really beautiful summary of what tests have failed as part of the `fastlane.ci` user interface, and make it expandable, link to the source code, and probably a lot of other cool things 👍

This is what makes the difference between a generic CI system, vs a mobile-optimized system 😀

**Comment by Ashraf-Ali-aa** [comment]
@KrauseFx it would be really good to use a generic file result parsing like https://github.com/hive-ci/res this way it can support multiple file formats and different frameworks, currently this is being used for the Hive CI also this looks promising https://github.com/TitouanVanBelle/XCTestHTMLReport

**Comment by Ashraf-Ali-aa** [comment]
currently is not in active development but what it does is converts results files like Junit to a JSON format in order to standardise the results that can be passed to different systems. I was planning on adding xctest test summary support.
