### ISSUE TITLE
Login in Web Application

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#749]
#### Backend #753
- [x] JSON end point to login user and issue a JW Token
- [x] Enforce token auth all Data endpoints (except login of course) 
#### Frontend #752
- [x] Create Login Page Stub
- [x] Create Auth service that handles server login
- [x] Store JWT in local storage
- [x] Attach JWT to all outgoing HTTP requests
- [x] Add Listener to all data service methods to redirect to login if `401` is returned. Maybe `HttpInterceptor`?
- [x] Store expiry date of the token in order to determine if the user's token is still valid.

**Comment by minuscorp** [comment]
Are we thinking on using [JWT Tokens](https://github.com/auth0/angular-jwt)?

**Comment by nakhbari** [comment]
I do think we might want to move to JWT tokens in the near future.

**Comment by minuscorp** [comment]
Not for now? For now just plain session token?

**Comment by KrauseFx** [comment]
I heard some really good things about JWT tokens, especially from orta https://twitter.com/orta/status/798457085872799744

I haven't looked into how they look exactly and if they were useful for us, but from what I understand, we could avoid the need for creating separate user accounts as we currently do. 

I don't know enough about it yet, but I think it might be worth looking into

**Comment by minuscorp** [comment]
Maybe we should split this issue into smaller ones (front-end vs back-end)?

**Comment by nakhbari** [comment]
@minuscorp Yes! Let me do that

**Comment by nakhbari** [comment]
Done, added a separate issue for account creation https://github.com/fastlane/ci/issues/1011
