### ISSUE TITLE
Build Artifacts

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#75]
Find the full documentation of this over here https://github.com/fastlane/ci/blob/master/docs/ArtifactsAndBuilds.md

**Comment by KrauseFx** [comment]
Find the full documentation of this over here https://github.com/fastlane/ci/blob/master/docs/ArtifactsAndBuilds.md

**Comment by KrauseFx** [comment]
Just to update everyone, @minuscorp started work on this

**Comment by jcampbell05** [comment]
Looked at the documentation, and figuring out if I can use the metadata to build a nice UI :)

**Comment by minuscorp** [comment]
I'll try to, at least, document or mock up how this is going to be done during the next week, so other people can start thinking on how to connect mi pieces with the UI @jcampbell05 😉

**Comment by jcampbell05** [comment]
@minuscorp That will be useful :) from what I can tell the API will just provide a list of artifact groups, the artifacts within those groups and where they are located so the metadata can be fetched :) 

Abstracting away Dropbox, AWS etc.

**Comment by taquitos** [comment]
Also, it might be helpful to have some UI component for displaying/accessing the artifacts on a per-build basis in `project.erb`. Right now we don't display any of that.

**Comment by jcampbell05** [comment]
@taquitos so the way I imagine it is you can filter artifacts by project or branch. you automatically see artifacts for every build :). 

:) going to get an example project up and running.

**Comment by KrauseFx** [comment]
I think the first version should just be a list of all available artifacts when opening the build details (one build of a given project). My feeling is that it might be a little tricky to start working on right now, as I'm currently working on build output, and @minuscorp started working on the build artifact architecture. So it sounds like the UI for the build artifacts would be a very small task?

@taquitos do you have an idea on what's the best way to start this?

**Comment by minuscorp** [comment]
Progress in #205

**Comment by jcampbell05** [comment]
:) sweet is there a way of getting a list of builds yet in the API ? @KrauseFx  ?

**Comment by minuscorp** [comment]
Here @jcampbell05 ! https://github.com/fastlane/ci/blob/09fcb825e52634530484bf899058ab9afb209f00/features/project/project_controller.rb#L83

`Project` has an array of `Build` in the `builds` attribute.

**Comment by jcampbell05** [comment]
@minuscorp sweet, I think we can build a pretty nice UI using this

**Comment by minuscorp** [comment]
Can we close this? #205 is already merged 😄

**Comment by KrauseFx** [comment]
Yesss 👍
