### ISSUE TITLE
[frontend] Login in Web Application

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#752]
Parent Issue: #749 

- [x] Create Login Page Stub
- [x] Create Auth service that handles server login
- [x] Store JWT in local storage
- [x] Attach JWT to all outgoing HTTP requests
- [x] Add Listener to all data service methods to redirect to login if `401` is returned. Maybe `HttpInterceptor`?
- [x] Store expiry date of the token in order to determine if the user's token is still valid.

**Comment by minuscorp** [comment]
> Check user authenticated on page load?
I've read that a good approach is to prompt for user login as a modal form (just as we do for creating a new project) whenever the authentication is wrong for certain request. That way we always make sure we're not redirecting the user to a login page whenever is not necessary (i.e., user is not logged in at all, it should be redirected to `/login`) and the user can continue where he left everything after the token being refreshed.

**Comment by nakhbari** [comment]
Done, added a separate issue for account creation https://github.com/fastlane/ci/issues/1011
