### ISSUE TITLE
[backend] Login in Web Application

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#753]
Parent Issue: #749 

- [x] JSON end point to login user and issue a JW Token
- [x] Enforce token auth all Data endpoints (except login of course)

**Comment by minuscorp** [comment]
Someone wants this or can I grab it?😁

**Comment by nakhbari** [comment]
Go for it!

**Comment by nakhbari** [comment]
@minuscorp Have we enabled the token enforcement yet? I don't see the JwtAuth class being referenced anywhere.

**Comment by minuscorp** [comment]
Nope, I think at some point we decided to first implement it and later on make use of it, so the login wouldn't block the rest of the tasks opened for the frontend. It is written as a middleware so it is just a one-liner to make use of it if you think that we're prepared to enable it 😄

**Comment by nakhbari** [comment]
OK, can we make a PR for this so we can test it out. Just realized that https://github.com/fastlane/ci/pull/794 is still waiting for review. Thought it was merged.

**Comment by minuscorp** [comment]
It can be tested rebasing on `master` so we can merge it? 😄

**Comment by nakhbari** [comment]
Good news i checked out the login with JWT and all things look great. We should be able to now enforce it on the `/data` JSON controllers.

@minuscorp is this something you want to take on?

Gonna update the issue description

**Comment by minuscorp** [comment]
I'll get this for next week! Give it to me😁

**Comment by minuscorp** [comment]
#872

**Comment by minuscorp** [comment]
This is ready to be closed 😄 https://github.com/fastlane/ci/pull/872
