### ISSUE TITLE
Make personal api token generation as easy as possible

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#76]
- [x] What scopes do we need?
- [x] Can we automate it?
- [x] How do we capture it

**Comment by KrauseFx** [comment]
This card is blocked for now, we reached out to GH to get a better sense of how we can do that to make it easy for our users 👍

**Comment by KrauseFx** [comment]
Described in detail in https://github.com/fastlane/ci/blob/master/docs/use_cases/first_time_setup.md

Gonna be built by @AndrewMcBurney
