### ISSUE TITLE
[Discussion] When and how to save changes in configuration files

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#764]
Based on https://github.com/fastlane/ci/pull/745, it seems like we never even commit any changes to `users.json` inside the `ci-config` repo. As a result, it's the same for the environment variable management I work on with https://github.com/fastlane/ci/pull/747

A few questions

1. Does each `*_service` need its own `commit_repo_changes!` method?
1. Do we call `commit_repo_changes!` every single time we update a value? First thought from my side is `yes`, especially since the `file_to_commit` parameter for `GitRepo.commit_changes!` isn't implemented yet, and we'd then commit random other files that were changed potentially hours or days ago
1. If not each `*_service` should have its own method, where should we put it?

Byeeeee

**Comment by minuscorp** [comment]
This purpose is for what I designed #459 #559 if someone wants to take a look

**Comment by KrauseFx** [comment]
Ahhh got it! Makes sense. I think now is a good time to go ahead with them. Which of the 2 PRs should I review?

**Comment by minuscorp** [comment]
#359 defines the operators and how to work with them, #459 is a use-case of them in the `ProjectService` (as an example of usage of the operators).

**Comment by KrauseFx** [comment]
It looks like they're the exact same 😉

**Comment by KrauseFx** [comment]
Unassigning me, as I think @snatchev had some opinions on this task?
