### ISSUE TITLE
Add new project flow

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#77]

**Comment by KrauseFx** [comment]
## Current state:

<img width="827" alt="screenshot 2018-02-11 02 10 33" src="https://user-images.githubusercontent.com/869950/36079191-577c6624-0f35-11e8-8c61-efebc0f244a9.png">

---

<img width="899" alt="screenshot 2018-02-11 02 10 47" src="https://user-images.githubusercontent.com/869950/36079193-5e6988f4-0f35-11e8-9fbe-a95b340f7b22.png">

## Ideal first flow

- Click the `Add new project` button, it lists all the orgs you have access to. 
- After selecting the org, it unfolds the repos of this org. (in the beginning just a simple list of all repos is fine also, like it's the case now)
- When selecting the repo, it should create and persist that project information in `projects.json`
- It should trigger the first CI run (this should probably wait for the TaskQueue implementation by @taquitos next week)
- It should open the project details (the work in progress build should be visible)

Once we have real-time logs for the build output, we of course want to open the log, not the project details

**Comment by KrauseFx** [comment]
@minuscorp that's something you want to work on still? If so, I assigned the issue to you for now 👍 Feel free to remove yourself it you're not interested

**Comment by minuscorp** [comment]
So in the PR I have opened I'm working towards building strong foundations, the final objective of the PR is to create the enough functionality in to be able to implement this, but I'll need time, there are many pieces to match! 🤓

**Comment by KrauseFx** [comment]
Beautiful, let's leave your face on this issue then, so that no one takes it away 😉

**Comment by taquitos** [comment]
@minuscorp if you want to, you could break this issue into a few issues, some issues covering whatever tasks are needed for backend work, and some issues covering whatever frontend work is needed.

**Comment by minuscorp** [comment]
Yeah, that may be helpful for everyone, as for the moment I'm not taking care about the frontend, tomorrow I'll break this in more little pieces 😁

**Comment by minuscorp** [comment]
Should we close this? Maybe we should refactor the issue to invite people to work on different steps of the Add Project use case.

**Comment by KrauseFx** [comment]
Yeah, sounds great, go ahead @minuscorp 👍
