### ISSUE TITLE
Implement onboarding

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#784]
This issue will basically include all the tasks needed to implement the fastlane.ci onboarding with the new front-end system 👍 

- [x] Endpoint to determine whether or not the server needs to be configured
- [x] Point to Onboarding page when server needs configuration on web app init
- [x] Onboarding Page Mocks

#### Frontend
- [x] Route to onboarding when server is not configured
- [x] Add stepper to onboarding page
- [x] Add encryption key input
- [x] Add bot account setup
- [x] Add ci config repo setup
- [ ] Add user account setup
- [ ] Send request to configure the server
- [ ] Add 5 char validation to encryption token
- [ ] Route to Dashboard
- [ ] Get proper screenshot of github permissions including email scope
- [ ] Update UI to new mocks

#### Backend
- [ ] JSON POST endpoint to create config repo #1012
- [ ] JSON POST endpoint to set Encryption key
- [ ] JSON POST endpoint to set OAuth info
- [ ] JSON GET to get the clientId
- [ ] JSON GET to get the GitHub auth token from a given code
- [ ] Change Auth in backend to verify that the passed token has access to all the repos required to complete any JSON Request
- [ ] (Lower priority) Endpoint that replies whether or not a config repo exists in the selected org
- [x] JSON GET to get the User's email associated with their account set up #1010

**Comment by nakhbari** [comment]
We're gonna need a way to know when the CI hasn't been setup yet.

I think @taquitos suggested we make a `/onboard` url and indicate in our Repo that they must go there first for now.

**Comment by taquitos** [comment]
I think we should have an endpoint that our frontend queries for an initial payload that contains things like localization info, and other constants that the server should be providing. As part of that payload, we should also indicate whether the server is totally setup and ready.
