### ISSUE TITLE
🚀 Working towards a successful beta launch

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#785]
This issue described the `Beta` milestone https://github.com/fastlane/ci/milestones/14

For the beta release, `fastlane.ci` is ready to be used & stable, however maybe not 100% battle-tested for larger setups yet

### Main pieces missing for a successful beta release

**Backend**

- ~~Support for distributed builds (https://github.com/fastlane/ci/issues/457 in progress @snatchev @bogdanbrato)~~
- Management of Xcode installations for the user (https://github.com/fastlane/ci/issues/446 **blocked** by distributed builds)
- Automatic commit of changes to `ci-config` repo (https://github.com/fastlane/ci/pull/459 and https://github.com/fastlane/ci/issues/71 **no one assigned**)
- Stability updates (~~https://github.com/fastlane/ci/issues/758~~, https://github.com/fastlane/ci/issues/711, https://github.com/fastlane/ci/issues/701, ~~https://github.com/fastlane/ci/issues/700~~, https://github.com/fastlane/ci/issues/613 and more @taquitos and anyone who wants to help)
- ~~Update mechanism for fastlane.ci (https://github.com/fastlane/ci/issues/445 @krausefx)~~
- ~~Store additional metadata for builds (https://github.com/fastlane/ci/issues/570 and https://github.com/fastlane/ci/issues/481 @KrauseFx)~~

**Frontend**

- Build details page (https://github.com/fastlane/ci/issues/709 **in progress**)
- Account Creation (#1011 **in progress**)
- Project details page (#682 **in progress**)
- Dashboard landing page (https://github.com/fastlane/ci/issues/644 **in progress**)
- Error handling (https://github.com/fastlane/ci/issues/578)
- Implement onboarding for the new frontend (https://github.com/fastlane/ci/issues/784 **in progress**)
- Manage global ENV variables with new frontend (https://github.com/fastlane/ci/issues/787)
- ~~fastlane.ci login (https://github.com/fastlane/ci/issues/749)~~
- ~~Support for streaming fastlane output to the new frontend (https://github.com/fastlane/ci/issues/786)~~

**General**

- Go through all the remaining `# TODO` items and make sure nothing is blocking (https://github.com/fastlane/ci/issues/464)

You can find the currently aimed "Due Date" in the [GitHub milestone](https://github.com/fastlane/ci/milestone/14) 🎉

**Comment by nakhbari** [comment]
@KrauseFx @taquitos Do you think we should add the splitting of the commit and PR trigger to the requirements for Beta. That seems pretty important to me.

**Comment by taquitos** [comment]
@nakhbari is there an issue you can point to around this? I'm not sure I understand what you mean
