### ISSUE TITLE
Manage global environment variables in the new frontend

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#787]
Basically the view of `/environment_variables_erb` ideally listing, adding, editing and deleting global ENV variables

**Comment by nakhbari** [comment]
Do we want a whole different page for all the ENV vars, or would we want to have the ability to edit them on each level (project level and CI top level)?

**Comment by KrauseFx** [comment]
I think we can follow what we wrote up in the our use cases with

- [edit_global_env_variables.md](https://github.com/fastlane/ci/blob/master/docs/use_cases/edit_global_env_variables.md)
- [edit_project_env_variables.md](https://github.com/fastlane/ci/blob/master/docs/use_cases/edit_project_env_variables.md)

Basically the project level ENV variables would be on a project settings level, while the other one is global, somewhere in the `fastlane.ci` global settings (or whatever we decide to call it or how we implement it)

Let me know if those docs have enough information, or if I should update them to describe things in more detail 👍
