### ISSUE TITLE
Wizard for creating a github account for the CI user

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#79]
- [ ] Is it possible to somehow create github account for fastlane.ci?
- [x] Ensure proper scopes for fastlane.ci github user

**Comment by KrauseFx** [comment]
This card is blocked for now, we reached out to GH to get a better sense of how we can do that to make it easy for our users 👍

**Comment by KrauseFx** [comment]
Described in detail in https://github.com/fastlane/ci/blob/master/docs/use_cases/first_time_setup.md

Gonna be built by @AndrewMcBurney
