### ISSUE TITLE
Intermittent connection error causes server to become unstable

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#798]
`[2018-05-02 17:10:06] DEBUG GitHubService:  Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known)`

`[2018-05-02 17:12:37] ERROR CheckForNewCommitsOnGithubWorker:  [FastlaneCI::CheckForNewCommitsOnGithubWorker Exception], work unit caused exception: Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known): 
`

**Comment by KrauseFx** [comment]
Should this be part of the Beta or 1.0 milestone?

**Comment by minuscorp** [comment]
Gonna add [Faraday Retry](https://github.com/lostisland/faraday/blob/master/lib/faraday/request/retry.rb) middleware to `Octokit` stack to prevent this kind of issues in a PR soon (this evening)

**Comment by taquitos** [comment]
I don't know if adding `Faraday Retry` is the right solution. This is likely caused by a GitHub outage, or maybe CDN rate limiting.

To really fix this issue we need to fix our workers so that they can handle more problems with networking in a graceful way.
- potentially recognizing problems that can't be fixed by retry, and deferring work
- heuristics for intelligently scheduling work in the future when we can try again (not just right after a failure, but rather, understanding what is happening and making a decision on what to do)
- Anything we do should also be built with this in mind: https://github.com/fastlane/ci/issues/802

**Comment by taquitos** [comment]
Yeah, I'd feel a lot better if we could unify it all into a more robust handler that is centralized in 1 single location.
That way we control all the retry logic, and it's easy to understand it because you don't have to go looking for it.

**Comment by taquitos** [comment]
Some mitigation is in place, but when the retries fail, this will still fail.

**Comment by minuscorp** [comment]
Yep, auto-closed by Github 😅
