### ISSUE TITLE
Wizard for creating a private configuration repository

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#80]
- [ ] Sanity test all configuration before moving on

**Comment by KrauseFx** [comment]
When launching and using fastlane.ci for the first time, we should help the user create a new private repo (right now, we're gonna focus just on GitHub, see fastlane.ci vision). 

Basically right now, fastlane.ci won't start at all when not having a git config repo, as we haven't planned the onboarding experience yet. For the time being, I guess it would be enough to have the doc available as part of the main README, and then telling the user to set it as the ENV variable for the `FASTLANE_CI_REPO_URL`, and then as Josh mentioned, do some checks. In the beginning those checks could be as simple as:
- Can I read and write on that repo
- Is the repo empty

@taquitos let me know if there was anything else you were thinking about on this one 👍

**Comment by taquitos** [comment]
I think for the time being that is ok. 

We definitely want to keep this in the MVP though, so anybody who wants to work on a wizard for creating a private config repo is totally 💯 free to pick this up and make the first-use experience awesome because we can't ship the MVP without it!

**Comment by AndrewMcBurney** [comment]
Closed in #275

**Comment by KrauseFx** [comment]
yesss 🚀
