### ISSUE TITLE
Split the functionality of commit trigger to commit and PR triggers

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#814]
We should split out the functionality what we have defined as a commit trigger today into 2 separate triggers. 1 for commits on a specific branch and another for all PRs.

Use Cases:
1) when a commit is tested in a PR, it is not at the same HEAD as master per say. So there might be some logic that is incompatible once merged, but passes in the feature branch.
2) I imagine it would be nice to have a source of truth history of your master branch when it comes to tests. This would help with regressions.
3) I believe there are lanes people want to run on commits to a branch rather than all PRs and commit. For example a slack notification.

**Comment by taquitos** [comment]
AHhhhhhhh I get it now. I was being dense. Yeah. We should do that. 

1. The commit trigger should only care about the commit on whatever branch is specified pointed at.
2. The PR trigger should apply to all branches (which seems to be normal behavior for CI systems).
3. A lot of our infrastructure will need to be renamed (and reworked a little), examples: `TRIGGER_TYPE` needs to be updated to include `PR`, `CheckForNewCommitsOnGithubWorker` needs to be updated to only look for commits on a branch, and then `CheckForNewPRsOnGithubWorker` needs to do what `CheckForNewCommitsOnGithubWorker` does right now.

**Comment by nakhbari** [comment]
@taquitos Were you thinking beta or v1? I'm thinking beta but it's a lot of work.

**Comment by taquitos** [comment]
I'm leaning towards V1 since the most common use case is PR checking, and it's a reasonably large chunk of work with significant potential to break something.

**Comment by KrauseFx** [comment]
It's your call @nakhbari @taquitos - I assigned 1.0 for now to make sure it's not unassigned (unassigned might get lost), and feel free to update it to whatever milestone you think makes sense 👍

**Comment by nakhbari** [comment]
My worry about pushing it to v1 is that those who use beta and upgrade to v1 will have their projects be triggered differently from before.

Ex. User chose commit trigger, builds trigger on commit + PR, User upgrades, User's project only builds on commits now since PR is a different trigger.

If y'all think this isn't a big deal or that it would be easy to be backwards compatible then I have no qualms with pushing it out to v1 👍

**Comment by KrauseFx** [comment]
Sounds good, let's move it to Beta then, and we can always move it back to 1.0 if we decide it's not as important
