### ISSUE TITLE
Define version numbers for each dependency in our Gemfile

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#820]
The goal is to define each dependency like this:
```ruby
gem "thin", ">= 1.7.2", "< 2.0.0"
```

Do not use `~` and of course don't define any version at all. The reason why we don't want to use `~>` is that it doesn't work nicely with new feature releases, usually we're fine with new feature releases (minor), but not with breaking releases (major), so by specifying the `>=` in combination with `<` we can accomplish exactly that 👍

**Comment by snatchev** [comment]
In the example above, I believe the same can be accomplished with:
```ruby
gem "thin", "~> 1.7"
```

As far as I understand, leaving off the patch bit, you will get any gem version from 1.7.x up to, but not including 2.x.x.

I do agree with the philosophy of including feature versions in the lockfile. It would be neat to have a cop to enforce this :)

**Comment by KrauseFx** [comment]
Yes, you're right, this works, however it comes with one problem: e.g. we tested with `1.7.2` that includes a critical bugfix, there is no way to specify with `~`, to have `1.7.2` and up, but below `2.0`

**Comment by snatchev** [comment]
Ah, yes! Perfect.

**Comment by KrauseFx** [comment]
This is resolved now 🥇
