### ISSUE TITLE
Change JSON deserialization to allow required parameters in model object constructors for models with the `JSONConvertible` mixin.

### ISSUE THREAD

**Issue by AndrewMcBurney** [fastlane/ci#822]
I came across this issue when tackling #817.

[This line](https://github.com/fastlane/ci/blob/master/app/shared/json_convertible.rb#L73) in `from_json!` in the `JSONConvertible` module creates a new object instance, with no parameters.

Hence, we can not have required parameters in our model constructors. Right now, we have [a bunch of optional parameters](https://github.com/fastlane/ci/blob/master/app/shared/models/user.rb#L14) with default values (usually set to `nil`).

Currently, in our deseralization method, we use `attr_accessor`s to set the values of the instance variables after object instantiation.

Some problems with this approch are:
- Some of these properties should be `attr_reader` only (such as `id`). Currently, a model's `id` could be arbitrarily set wherever since we're exposing a setter method.
- A model could be instantiated without the necessary parameters, and not fail explicitly (i.e., creating a `User` without an `email`, or without a `password_hash`).

<img width="620" alt="screen shot 2018-05-07 at 1 25 37 pm" src="https://user-images.githubusercontent.com/8942499/39715238-a33f68e2-51fa-11e8-8523-1486245dcff6.png">

**Comment by minuscorp** [comment]
This is actually a tricky one, specially with the `attr_*` attribute family. I will dig into this and open a PR soon 😄

**Comment by minuscorp** [comment]
Just a quick mock-up of what I was thinking on: https://repl.it/@minuscorp/ComplexMaleCircle

**Comment by AndrewMcBurney** [comment]
Yeah, that looks great @minuscorp!! 🙌

**Comment by KrauseFx** [comment]
Yes, I noticed that also, and made all parameters for the initializer optional as a result... Sounds like an area for improvement 👍

**Comment by minuscorp** [comment]
Moved the discussion to #833
