### ISSUE TITLE
Can not run in docker

### ISSUE THREAD

**Issue by chaim1986** [fastlane/ci#830]
mac-pro:ci chaim$ docker  version 
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
mac-pro:ci chaim$ 

------error log . --- 

mac-pro:ci chaim$ docker-compose up --build
Building web
Step 1/9 : FROM ruby:2.5
 ---> fb664b54b956
Step 2/9 : ENV LANG C.UTF-8
 ---> Using cache
 ---> 2c19102643b6
Step 3/9 : RUN bundle config --global frozen 1
 ---> Using cache
 ---> 039cb016eb93
Step 4/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 7503a14ad782
Step 5/9 : COPY Gemfile Gemfile.lock ./
 ---> Using cache
 ---> 12bbaddd71a9
Step 6/9 : RUN bundle install
 ---> Using cache
 ---> d01316a66c22
Step 7/9 : COPY . .
 ---> Using cache
 ---> c8aced358a72
Step 8/9 : CMD ["prod"]
 ---> Using cache
 ---> 4e8724ebdd5f
Step 9/9 : ENTRYPOINT ["bundle", "exec", "rake"]
 ---> Using cache
 ---> ba1b3775dce6
Successfully built ba1b3775dce6
Successfully tagged ci_web:latest
Starting ci_web_1 ... done
Attaching to ci_web_1
web_1  | bundle exec rackup -p 8080 --env production
web_1  | warning: parser/current is loading parser/ruby25, which recognizes
web_1  | warning: 2.5.0-compliant syntax, but you are running 2.5.1.
web_1  | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
web_1  | RuntimeError: The web app not built. Build with the Angular CLI and Try Again, e.g. ng build --deploy-url="/.dist"
web_1  |   /usr/src/app/launch.rb:55:in `verify_app_built'
web_1  |   /usr/src/app/launch.rb:22:in `take_off'
web_1  |   /usr/src/app/config.ru:8:in `block in <main>'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
web_1  |   /usr/src/app/config.ru:in `new'
web_1  |   /usr/src/app/config.ru:in `<main>'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/lib/rack/server.rb:148:in `start'
web_1  |   /usr/local/bundle/gems/rack-2.0.5/bin/rackup:4:in `<top (required)>'
web_1  |   /usr/local/bundle/bin/rackup:29:in `load'
web_1  |   /usr/local/bundle/bin/rackup:29:in `<top (required)>'
web_1  | bundler: failed to load command: rackup (/usr/local/bundle/bin/rackup)
web_1  | rake aborted!
web_1  | Command failed with status (1): [bundle exec rackup -p 8080 --env productio...]
web_1  | /usr/src/app/Rakefile:6:in `block in <top (required)>'
web_1  | /usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
web_1  | /usr/local/bundle/bin/bundle:104:in `load'
web_1  | /usr/local/bundle/bin/bundle:104:in `<main>'
web_1  | Tasks: TOP => prod
web_1  | (See full trace by running task with --trace)
ci_web_1 exited with code 1
mac-pro:ci chaim$

**Comment by KrauseFx** [comment]
Thanks for reporting this, I guess that's because we haven't yet updated the docker container to automatically build the angular based frontend. Docker support was initially added by @adellibovi with https://github.com/fastlane/ci/pull/619, we haven't worked on it since then.

May I ask why you want to run a Docker container, considering that you'll need a macOS host anyway to be able to compile an iOS project?

**Comment by adellibovi** [comment]
@KrauseFx I will have a look at this, it’s definitely because we didn’t update for angular.

**Comment by chaim1986** [comment]
@KrauseFx  I just have a try use the ci with docker on the mac os .. anyway fastlane work with docker  is a cool idea.. :)
