### ISSUE TITLE
general Xcode/tool problems affecting the whole server

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#84]
If there are Xcode or other tool issues that are impacting the server as a whole, we need to figure out the best way to notify people
- [x] Dashboard banner?
- [x] Pager-duty?
- [x] Github Issue creation?
- [x] Attempt to fix common problems (xcode-install)?

**Comment by KrauseFx** [comment]
I think email would probably the most generic, most common one we could start with. And then we can go from there. And agreed, the first integration (e.g. email) should already be built in a way to allow developers to hook in their own systems, maybe just allowing running a shell script in the beginning

**Comment by taquitos** [comment]
I was even thinking, just for a MVP of this issue, persisting the notifications somewhere and getting a dashboard banner that you can acknowledge/dismiss

**Comment by KrauseFx** [comment]
Yeah, that's a great idea 👍 Sending emails is still a pain nowadays, so your approach might be the best one to get started with
