### ISSUE TITLE
[Proposal] System to allow system-wide preferences

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#870]
Without having a clear specification of this feature yet, I want to get the discussion started.

It seems like we'll have some system settings that are system wide, but don't deserve their own configuration file. Some examples I can think of:

- Default Xcode version
- Default Apple ID to use (e.g. for installing Xcode)
- Boolean options like:
  - Automatically install new versions of Xcode
  - Automatically maintain local simulators
  - Disable metric collections
- fastlane.ci web host URL (`FASTLANE_CI_BASE_URL`)
- Many more in the future probably

Should we introduce a `settings.json` in the root of the `ci-config` repo that contains all those attributes? If so, we should have a system built-in to override any value on a project/branch level (branch overrides can be post 1.0 feature)

We already have project-level overrides for ENV variables with https://github.com/fastlane/ci/pull/768, so we could something similar in a more generic way.

Ideally the `settings.json` is a hash that allows any key/value pair that we define in a single `.rb` file, as it should be easy for us to add new options without having to write duplicate code. 

A `settings.json` for those settings will also allow us to tell the user to modify the JSON file directly, for hidden options (options that we support, but don't have a full UI yet), so we can iterate faster and show what's most relevant to the user, while still putting the user in full control over everything.

---

### Proposal

Based on the description above it seems like we could do the following:

Simplified Ruby interface
```ruby
class Settings
  attr_accessor :metrics_disabled
  attr_accessor :install_new_versions_of_xcode
  attr_accessor :default_apple_id
  ...
end
```
those are automatically mapped to be stored in a `settings.json` file:
```json
{
  "metrics_disabled": false,
  "install_new_versions_of_xcode": true,
  "default_apple_id": "apple@krausefx.com"
}
```
we could even use JSON comments when generating the file during the setup to allow anyone to modify the values without even having to read the docs. There are multiple ways to provide comments in JSON, either by not following the JSON standard and using `/* ... */` or by wrapping the value in another hash:
```json
{
  "metrics_disabled": {
    "value": false,
    "comment": "Don't collect any metrics, more information on privacy at https://privacy.fastlane.ci"
  },
  "default_apple_id": {
    "value": "apple@krausefx.com",
    "comment": "What Apple ID should be used to install Xcode"
  }
}
```

Looking at the above used example settings, it doesn't seem to make sense to allow an override on a project level, as those attributes really are on a system level. It might make sense to allow overriding some of the values, all of this is possible to also implement in the future. For now, I'd propose focusing on the system-level settings, and go from there

**Comment by snatchev** [comment]
What is the intended interface for a user of fastlane.ci to change their server settings? Via web UI or text editing? Would the server generate a file when it's install/boots?

**Comment by snatchev** [comment]
Overall, my first inclination would be to use YAML for a comment-able, human readable, key-value text format. That being said, I think a mix of formats is not great either. This might be negligible if the interface is a web UI, and JSON is just used for saving/exporting values.

**Comment by KrauseFx** [comment]
> What is the intended interface for a user of fastlane.ci to change their server settings? Via web UI or text editing? Would the server generate a file when it's install/boots?

Yeah, so that's the beauty of text-based configuration files: we can offer a UI for some of the options (e.g. Analytics opt-out), and have "secret" options that are less popular be via text file modification until we have a proper UI for them (if ever). 

Yes, I'd think fastlane.ci creates the file when it sets up the repo (as it also creates the other config files). 

> Overall, my first inclination would be to use YAML for a comment-able, human readable, key-value text format. That being said, I think a mix of formats is not great either. This might be negligible if the interface is a web UI, and JSON is just used for saving/exporting values.

Yah we should stick with consistent JSON, I'd think that 90% of all users never ever have to open this file, as we'll offer a web UI for the most common options. It really is just for more advanced configurations and edge cases where you'd have to manually edit this file.
