### ISSUE TITLE
Add GitHub Checks Support

### ISSUE THREAD

**Issue by aamct2** [fastlane/ci#899]
GitHub has added major improvements for viewing CI results thanks to the new Checks API. It would be great to support this.

Reference links:
- https://blog.github.com/2018-05-07-introducing-checks-api/
- https://developer.github.com/changes/2018-05-07-new-checks-api-public-beta/
- https://developer.github.com/v3/checks/

**Comment by KrauseFx** [comment]
I'd love to add this to fastlane.ci, however from what I understand

> The Checks API is only available to GitHub Apps through a new granular permission: checks.

And fastlane.ci can't be a GitHub App, as it's completely self-hosted without a central instance 😢

**Comment by KrauseFx** [comment]
If it's cool, I'll close this issue for now, as there is nothing we can do. As soon as the API is publicly available, let's re-open 👍

**Comment by aamct2** [comment]
@KrauseFx I've done a fair bit of reading of the GitHub App docs. Unless I've missed something, it should work for Fastlane CI, even self-hosted.

I don't think Fastlane CI could set up in the Marketplace without a centrally managed instance. But that shouldn't prevent it from becoming a GitHub App and supporting the Checks API.

**Comment by KrauseFx** [comment]
Mh, interesting - I think we investigated the use of GitHub apps when we first started working on the authentication bit of fastlane.ci, and learned that it's not possible to make use of those features without having a centralized instance in the middle somewhere. Maybe @taquitos remembers more on why that was?
