### ISSUE TITLE
[Xcode] Authorize Xcode installation

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#902]
Follow-up to Xcode PR https://github.com/fastlane/ci/pull/819

Implement asking for the root password as part of the installation (via KrauseFx/xcode-install#279)

**Comment by KrauseFx** [comment]
@snatchev mentioned that this might be solved depending on how we're gonna split up the workers. Any news on that?

**Comment by snatchev** [comment]
@KrauseFx lets tackle this problem when we're both in NYC.

**Comment by snatchev** [comment]
linking to: https://github.com/fastlane/ci/blob/master/docs/WorkerAgent.md#permission-model for reference / possible proposal.

**Comment by KrauseFx** [comment]
Yeah great idea, let's do it 👍
