### ISSUE TITLE
[Proposal] How should artifact storage be configured?

### ISSUE THREAD

**Issue by snatchev** [fastlane/ci#914]
fastlane.ci needs to persist artifacts from a build. Artifacts can include any output such .ipa files, logs and screenshots. Given that our new fastlane workers (a.k.a Agents) are designed to be lightweight and ephemeral, we need a way to send the outputs of a build somewhere for storage which can be anything from AWS, SFTP or a network file mount. 

I propose that this feature should be provided by fastlane itself and configured in the Fastfile. We already have a plugin that will upload to S3 here https://github.com/joshdholtz/fastlane-plugin-s3. Credentials will be passed in by the Agent via environment variables.

We will need a way to tie the artifact back to the build. We will need some kind of artifact reference (probably a URI) that we can use to go download the artifact. This artifact reference should be saved with the build.

When someone creates a new project with a Fastfile, fastlane.ci can notice that it is missing an artifact storage configuration and suggest a pre-defined lane for the user to accept and configure.

**Comment by minuscorp** [comment]
Actually, this is more or less how `ArtifactProvider` works now, it stores the artifact in a manner depending of which provider it is and retrieve the Artifact in some URL kind form. They're also attached to the build both the provider and the different artifacts. I don't know if I can provide some more info about how it is designed now (as I was who coded it).

**Comment by snatchev** [comment]
@minuscorp I assumed we'd be using the `ArtifactProvider` in this use case :). The gist of the proposal is that the actual business logic of moving the bytes to their destinations should live inside fastlane itself (possibly as a fastlane plugin) and not within the ci system.

**Comment by minuscorp** [comment]
I kind of feel that this logic should live in the CI's part, as I understand an `Artifact` as an inherent concept of a Continuous Integration system. But this is just a point of view 😅

**Comment by snatchev** [comment]
That's a good point. If we consider fastlane as a build system with build tasks and one of those build tasks is to upload a file somewhere. Suppose the upload fails for a network reason, now that "build" failed as part of the build system, but really the build succeeded and it could be considered the CI system's responsibility to move the artifact to the right place.

**Comment by minuscorp** [comment]
As I understand it, _fastlane_ is the responsible of creating the different `Artifact`s as it's been in the past. But the responsibility of gathering them and later on store them in whichever service it's CI's responsibility.

**Comment by KrauseFx** [comment]
Sounds like we're all on the same page: fastlane is responsible for uploading the artifacts, and then providing some kind of reference (ID, URL, etc.) back to fastlane.ci for each of the artifacts

**Comment by minuscorp** [comment]
I was kind of thinking of _fastlane_ just as a creator of _paths_ and the CI through the `ArtifactProvider` a creator of  `Artifact`s with its references.
