### ISSUE TITLE
Build Artifacts Endpoint

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#918]
Parent: #709 

Requirements:
- Artifacts
  - Name
  - Link to download

**Comment by nakhbari** [comment]
Looks like @KrauseFx did some work here: https://github.com/fastlane/ci/pull/927

Still need to figure out the best method to download the artifact.

My thoughts are to return the download link along-side the rest of the artifact data. 
The response would have the `download_url` whether it be hosted locally or in the cloud. 

Ex.
```json
[{
  "id": "123",
  "name": "best-file",
  "download_url": "https://cloud.storage.google.com/best-bucket/best-folder/best-file"
},
{
  "id": "1234",
  "name": "bestest-file",
  "download_url": "http://localhost:8080/api/artifact/1234/download"
}]
```

The difference here is that the web-app can be dumb and just reference whichever link the backend provides. And we wouldn't have to have the backend download the cloud hosted file and reserve it with it's own endpoint, reducing our traffic and the effective latency.

**Comment by KrauseFx** [comment]
Yeah I don't think we decided on the download yet, mostly because we didn't implement the upload yet for the fastlane.ci workers, this is blocked by the worker task going on right now https://github.com/fastlane/ci/pull/951 👍
