### ISSUE TITLE
frontend MIME checking strict error

### ISSUE THREAD

**Issue by LivioGama** [fastlane/ci#924]
Hello, on the latest version I get a white page after following instructions of installations without docker. The console shows : 
```
Refused to apply style from 'http://localhost:8080/styles.a10ccf2429c77a75d2fe.bundle.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:8080/inline.318b50c57b4eba3d437b.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:8080/polyfills.a7e8614283b1ade81941.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:8080/main.93ec3bcc0ef152d14aa4.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by KrauseFx** [comment]
Hey @LivioGama, thanks for helping out with fastlane.ci. Can you tell us a bit more of how you installed & set up fastlane.ci? That error is in your web browser, right? Is there anything in your server logs?

**Comment by LivioGama** [comment]
I installed rvm. I installed Ruby 2.3.3 though RVM.
git clone https://github.com/fastlane/ci
cd ci
npm install
npm run-script build
gem install bundler
bundle install
bundle exec rake prod

![screen shot 2018-05-24 at 16 16 03](https://user-images.githubusercontent.com/6930498/40491277-e7cd6d6c-5f6d-11e8-8b43-05331d6a6d12.png)

**Comment by KrauseFx** [comment]
Interesting - I don't know enough about this part of fastlane.ci, does this happen when you use `127.0.0.1` instead? Does this happen on a different browser also?

**Comment by KrauseFx** [comment]
Thanks for reporting this and sorry you're running into this problem, we'll get back to you later this week or next week 👍

**Comment by KrauseFx** [comment]
Did you ever run `ng build --deploy-url="/.dist" --dev -w`? If not, can you give this a try?

If that also doesn't work, you can run fastlane.ci after setting an ENV variable
```
export FASTLANE_CI_ERB_CLIENT=1
```

**Comment by nakhbari** [comment]
@LivioGama Our `npm run-script build` is not correct right now since it's missing the ` --deploy-url="/.dist"` flag. This is most likely the issue. Let me whip up a PR. In the meantime doing what @KrauseFx suggested should get you going 🚀 

`ng build --deploy-url="/.dist" --prod`

**Comment by LivioGama** [comment]
Thanks, it works ! Just a question, what are the login and password I'm asked to fill ? I didn't create any user and I get this : 
![capture d ecran 2018-05-30 a 16 38 08](https://user-images.githubusercontent.com/6930498/40727277-da802fa0-6427-11e8-8844-5648f00bc63a.png)
