### ISSUE TITLE
Accessing /login in a logged in state should redirect to the dashboard

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#934]
Steps to reproduce

1. Login
2. Access `http://localhost:9292/login`

Expected result: Redirect to dashboard
Actual result: Login is shown

**Comment by kevinsamoei** [comment]
How can one reproduce this, I don't think there is a way to register as a new user via the UI or is there an email and password that can be used for testing?

**Comment by KrauseFx** [comment]
Hey @kevinsamoei, see our comments on https://github.com/fastlane/ci/issues/924#issuecomment-393209605, right now the onboarding isn't implemented on the new frontend yet :)
