### ISSUE TITLE
Enable builds to have arbitrary key/value metadata called BuildContext

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#94]
There are many pieces of metadata that one might want to capture, or add to each build. For example: how many `TODOs` were found? 
To capture this data and provide flexibility for future plugin writers, let's add a scoped key/value storage location to the `build` object 
- [ ] generic storage mechanism for key/values based on some named scope (maybe plugin name)

**Comment by KrauseFx** [comment]
Full document available here https://github.com/fastlane/ci/blob/master/docs/ArtifactsAndBuilds.md

**Comment by minuscorp** [comment]
For me, here are two topics being raised.

1. Passing parameters to the _fastlane_ lane executed by a certain project, i.e., `project_1` with lane `build` and params: `upload_to: appstore`; `project_2` with lane `build` and params: `upload_to: testflight`. This is what I understand as `BuildContext`.

2. Plugins, allow to third party developers to create plugins _aka_ actions with functionality that can't be achieved through _fastlane_. I have read the [document](https://github.com/fastlane/ci/blob/master/docs/ArtifactsAndBuilds.md) that describes this and I find it kind of confusing. Let me explain, in that document you can find an example of extra information attached to a certain build, but for me, they are just `Artifact`s. The reason I say that is the source where it came from (i.e., a coverage report, might be generated by _fastlane_ itself, which has access to the source code and has the capability of generate files that _CI_ can classify as `Artifact`s). For me, a plugin **should just consume a `type` of `Artifact` and generate some kind of output into the `build` details page**. So I'm clearly thinking of plugins being able to generate some kind of templates that we can embed in the frontend itself.

Those are my thoughts, sorry for the long post, not feeling well today 🤒

**Comment by KrauseFx** [comment]
Interesting - maybe we're talking about 2 different things here. I think the idea for the key value store for builds is for `fastlane.ci` plugins to store extra information, not fastlane actions/plugins. 

As an example, for `fastlane.ci` itself, we probably want to attach the number of open `# TODO` items in the code base to the each build, so that we can easily render a graph of how that number changes over time. 

I'm not sure how the `1. ` question you describe is related to this issue?

**Comment by KrauseFx** [comment]
Actually, let me step back and meditate on this, I understand now, and you're right, those are some valid questions, I'll think of how we can potentially solve this 👍
