### ISSUE TITLE
How to change port 8080 to another one?

### ISSUE THREAD

**Issue by JayantVarma** [fastlane/ci#940]
How can I change the port from 8080 to anything else, there are other services that could be running and using 8080

**Comment by KrauseFx** [comment]
Hey @JayantVarma, you can run
```
bundle exec rackup --host 0.0.0.0 --port 8081 --env production
```
Let me know if that works 👍

**Comment by JayantVarma** [comment]
It's downloading the dependencies, I was running it in Docker, will update the outcome as soon as it is done

**Comment by JayantVarma** [comment]
on the MAC, I get
`warning: 2.3.5-compliant syntax, but you are running 2.3.4.`
and when I run rvm list I do not see 2.3.5 but do see 2.4.1

```
rvm rubies

 * ruby-2.1.2 [ x86_64 ]
   ruby-2.2.2 [ x86_64 ]
   ruby-2.3.3 [ x86_64 ]
=> ruby-2.3.4 [ x86_64 ]
   ruby-2.4.1 [ x86_64 ]
```

so it does not run locally on the mac

**Comment by KrauseFx** [comment]
It's a warning, I think it should still work just fine. Why do you run it on Docker? You won't be able to compile iOS apps then

**Comment by JayantVarma** [comment]
OK, but it would be nice to separate the processes. It further breaks with 
`ci/launch.rb:55:in `verify_app_built': The web app not built. Build with the Angular CLI and Try Again, e.g. ng build --deploy-url="/.dist" (RuntimeError)`
