### ISSUE TITLE
bundle exec rake prod error

### ISSUE THREAD

**Issue by baturorkun** [fastlane/ci#945]
c2mmini$ sudo bundle exec rake prod
bundle exec rackup --host 0.0.0.0 --port 8080 --env production
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
bundler: failed to load command: rackup (/usr/local/bin/rackup)
RuntimeError: The web app not built. Build with the Angular CLI and Try Again, e.g. ng build --deploy-url="/.dist"
  /Users/c2mmini/Downloads/ci/launch.rb:55:in `verify_app_built'
  /Users/c2mmini/Downloads/ci/launch.rb:22:in `take_off'
  /Users/c2mmini/Downloads/ci/config.ru:8:in `block in <main>'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
  /Users/c2mmini/Downloads/ci/config.ru:in `new'
  /Users/c2mmini/Downloads/ci/config.ru:in `<main>'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:283:in `start'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:148:in `start'
  /Library/Ruby/Gems/2.3.0/gems/rack-2.0.5/bin/rackup:4:in `<top (required)>'
  /usr/local/bin/rackup:22:in `load'
  /usr/local/bin/rackup:22:in `<top (required)>'
rake aborted!
Command failed with status (1): [bundle exec rackup --host 0.0.0.0 --port 8...]
/Users/c2mmini/Downloads/ci/Rakefile:6:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `load'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:424:in `exec'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => prod
(See full trace by running task with --trace)

**Comment by KrauseFx** [comment]
```
RuntimeError: The web app not built. Build with the Angular CLI and Try Again, e.g. ng build --deploy-url="/.dist"
```
Does that help?

**Comment by baturorkun** [comment]
ok thanks but

ng build --deploy-url="/.dist"  result:

Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at BuildCommand._loadWorkspaceAndArchitect (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:180:32)
    at BuildCommand.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:3:12)
    at BuildCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/command-runner.js:87:23)

**Comment by vjanssens** [comment]
Had the same problem. Running `npm i` before `ng build [..]` fixed it.

**Comment by KrauseFx** [comment]
Hey @baturorkun, can you confirm that @vjanssens' response helped? Sorry onboarding is still a little rough, we're working on making things easier 👍

**Comment by taquitos** [comment]
While this is sorted out, you can switch to use only the old-style ERBs with `FASTLANE_CI_ERB_CLIENT=1`

**Comment by hfossli** [comment]
I had to do:
```shell
bundle install
npm install
npm run ng build --deploy-url="/.dist"
bundle exec rake dev
```

(I didn't know how to run the `ng` command, now I know)

**Comment by nakhbari** [comment]
@hfossli I missed this, but it is recommended to do `npm run build` it will use the locally installed npm dependencies to build the app for you.

**Comment by AppleEducate** [comment]
@hfossli I had to do the following
```
bundle install
brew install node
npm install
npm run ng build --deploy-url="/.dist"
bundle exec rake dev
```
