### ISSUE TITLE
Cleanup build data after a certain limit

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#950]
To save disk space we should cleanup the repo clone used to run the build. @taquitos suggested a default limit of 20 builds to be kept in the history, any older build would be cleaned up in a separate thread/task since it could take time.

**Comment by nakhbari** [comment]
Maybe this could be apart of the new hotness `settings.json` file

**Comment by KrauseFx** [comment]
> To save disk space we should cleanup the repo clone used to run the build

What do you mean by that? Sorry I don't understand.

Like limit the number of `builds/[number].json` files?

**Comment by nakhbari** [comment]
Each build has a copy of the entire repo, including any build data that was created in that workspace during the fastlane command. As seen when doing something like `npm install` this can be quite costly when it comes to disk space. Those lingering files are what should be deleted. The actual build data we display (outcome, logs, artifacts) should remain intact.

**Comment by KrauseFx** [comment]
Ahh got it. Yeah I believe the workspaces can safely be cleaned after the build is finished and its artifacts were uploaded, right? This actually ties in with the new master/worker code
