### ISSUE TITLE
unable to build webapp due to incorrect reference in  dashboard.module.ts

### ISSUE THREAD

**Issue by notimewaste** [fastlane/ci#976]
Steps 

1.`cd web `
2.`ng build --deploy-url="/.dist"`

output 

`ERROR in web/app/common/components/common-components.module.ts(4,36): error TS2307: Cannot find module '../../shared_material.module'.
web/app/dashboard/dashboard.module.ts(12,36): error TS2307: Cannot find module '../shared_material.module'.`

**Comment by taquitos** [comment]
Fixed in https://github.com/fastlane/ci/pull/968
