### ISSUE TITLE
Signup /setup flow not working

### ISSUE THREAD

**Issue by WildStudio** [fastlane/ci#978]
I followed the instructions to get up and running the CI, but it haven't take me through a flow to set up a new CI user.

**Comment by KrauseFx** [comment]
Oh that's interesting. We're actually working on onboaring using the new frontend. Have you used the `FASTLANE_CI_ERB_CLIENT` ENV variable to use the legacy front-end for onboarding?

**Comment by WildStudio** [comment]
@KrauseFx No I haven't use that ENV variable. As soon as I ran the CI on localhost:8080 it prompted me with the login fields. I already set up the angular frontend as explained in the README. I don't know if it has something to do with but I had Jenkins running as a Daemon listening on port 8080.

**Comment by KrauseFx** [comment]
Yeah makes sense. Sorry we haven't finished onboarding on the new frontend yet. For now, can you launch the server using

```
FASTLANE_CI_ERB_CLIENT=1 bundle exec rackup
```

and see if that works (for onboarding). Once you set fastlane.ci up you can remove that ENV variable again
