### ISSUE TITLE
Encapsulate GitRepo exception handling and pull it out of git_repo.rb

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#980]
As we continue to move forward, it will be important to identify exceptions, post appropriate notifications so that users understand if this is something they need to care about, and to prevent the server from crashing.
Right now in `git_repo.rb` we have a method: `def handle_exception(ex, console_message: nil, exception_context: {})`
This currently handles all of that logic. We should pull this out somewhere because it's going to continue to grow and get more complicated. Also, it's a cross-cutting concern so I don't feel like stuffing it in the `GitRepo` is the right thing to do (which is what I've been doing 🤫)

**Comment by KrauseFx** [comment]
Maybe something to consider: as a follow-up to https://github.com/fastlane/ci/pull/951, we also need to use some of the git code we wrote on our worker. The worker is pretty basic and doesn't know a lot, however it needs to know about a GitRepo and how to clone/auth it. We created an issue with https://github.com/fastlane/ci/issues/966. 

Not sure if that's super relevant, just fyi
