### ISSUE TITLE
KrauseFx:patch-1 branch for google-cloud-ruby deleted

### ISSUE THREAD

**Issue by kerry** [fastlane/ci#984]
In Gemfile on the master, there is a dependency

Access to Google Cloud Platform Storage API.
`gem "google-cloud-storage", git: "https://github.com/krausefx/google-cloud-ruby", branch: "patch-1"`
TODO: Should be ">= 1.12.0", "< 2.0" once https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2099 is merged

But the patch-1 branch has already been deleted so this dependency fails to resolve.
Also, I saw that https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2099 will not merge and https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2129 is still open

Any resolution for this?

**Comment by KrauseFx** [comment]
Ahhh, nice catch, thanks, working on a fix

**Comment by KrauseFx** [comment]
Just merged https://github.com/fastlane/ci/pull/986, could you give it another try?
