### ISSUE TITLE
Step 5 fails (bundle install from Using fastlane.ci)

### ISSUE THREAD

**Issue by androuis** [fastlane/ci#985]
I got at step 5 from Using fastlane.ci: bundle install and it fails with this error:
Revision f71ec2e7a1eaf43c15312d611dd1cc4de530f823 does not exist in the
repository https://github.com/krausefx/google-cloud-ruby. Maybe you misspelled
it?

**Comment by KrauseFx** [comment]
Ahhh, nice catch, thanks, working on a fix

**Comment by KrauseFx** [comment]
Just merged https://github.com/fastlane/ci/pull/986, could you give it another try?

**Comment by androuis** [comment]
Yes. It works. Thanks :)

**Comment by KrauseFx** [comment]
Great to hear
